insert into pet (name, animal, race) values ('Ripley', 'Penguin, magellanic', 'Spheniscus magellanicus');
insert into pet (name, animal, race) values ('Rosalie', 'Wallaby, whip-tailed', 'Macropus parryi');
insert into pet (name, animal, race) values ('Sonny', 'Stork, yellow-billed', 'Mycteria ibis');
insert into pet (name, animal, race) values ('El', 'Raven, white-necked', 'Corvus albicollis');
insert into pet (name, animal, race) values ('Latisha', 'Marshbird, brown and yellow', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Kennedy', 'Marshbird, brown and yellow', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Channa', 'Hyena, striped', 'Hyaena hyaena');
insert into pet (name, animal, race) values ('Jamill', 'Common seal', 'Phoca vitulina');
insert into pet (name, animal, race) values ('Torey', 'Common zorro', 'Dusicyon thous');
insert into pet (name, animal, race) values ('Sean', 'Groundhog', 'Marmota monax');
insert into pet (name, animal, race) values ('Ludwig', 'Cat, african wild', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Temp', 'Roadrunner, greater', 'Geococcyx californianus');
insert into pet (name, animal, race) values ('Nobe', 'Sandhill crane', 'Grus canadensis');
insert into pet (name, animal, race) values ('Winslow', 'Coatimundi, white-nosed', 'Nasua narica');
insert into pet (name, animal, race) values ('Lexie', 'Rat, desert kangaroo', 'Dipodomys deserti');
insert into pet (name, animal, race) values ('Geri', 'Legaan, Monitor (unidentified)', 'Varanus sp.');
insert into pet (name, animal, race) values ('Markos', 'Ring-tailed possum', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Alvina', 'Australian masked owl', 'Tyto novaehollandiae');
insert into pet (name, animal, race) values ('Anthia', 'Indian red admiral', 'Vanessa indica');
insert into pet (name, animal, race) values ('Althea', 'Pelican, australian', 'Pelecanus conspicillatus');
insert into pet (name, animal, race) values ('Patric', 'Two-toed sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Jodi', 'Southern white-crowned shrike', 'Eurocephalus anguitimens');
insert into pet (name, animal, race) values ('Amalle', 'Hornbill, southern ground', 'Bucorvus leadbeateri');
insert into pet (name, animal, race) values ('Jordanna', 'Goose, greylag', 'Anser anser');
insert into pet (name, animal, race) values ('Sigismundo', 'Koala', 'Phascolarctos cinereus');
insert into pet (name, animal, race) values ('Benoit', 'Goose, cape barren', 'Cereopsis novaehollandiae');
insert into pet (name, animal, race) values ('Rhianna', 'Pygmy possum', 'Acrobates pygmaeus');
insert into pet (name, animal, race) values ('Shae', 'Macaque, japanese', 'Macaca fuscata');
insert into pet (name, animal, race) values ('Alvera', 'Heron, goliath', 'Ardea golieth');
insert into pet (name, animal, race) values ('Colly', 'Monkey, bleeding heart', 'Theropithecus gelada');
insert into pet (name, animal, race) values ('Tristan', 'Grey heron', 'Ardea cinerea');
insert into pet (name, animal, race) values ('Jade', 'Gull, dusky', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Alonso', 'Brown and yellow marshbird', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Rusty', 'Cape clawless otter', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Sarajane', 'Worm snake (unidentified)', 'Carphophis sp.');
insert into pet (name, animal, race) values ('Cyrus', 'Black-capped capuchin', 'Cebus apella');
insert into pet (name, animal, race) values ('Cece', 'Tamandua, southern', 'Tamandua tetradactyla');
insert into pet (name, animal, race) values ('Rubi', 'Porcupine, tree', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Cesya', 'Wolf, common', 'Canis lupus');
insert into pet (name, animal, race) values ('Lon', 'Pronghorn', 'Antilocapra americana');
insert into pet (name, animal, race) values ('Glori', 'Striped dolphin', 'Stenella coeruleoalba');
insert into pet (name, animal, race) values ('Sampson', 'Ring-tailed coatimundi', 'Nasua nasua');
insert into pet (name, animal, race) values ('Zulema', 'Bear, american black', 'Ursus americanus');
insert into pet (name, animal, race) values ('Barret', 'Bird, black-throated butcher', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Ly', 'Whip-tailed wallaby', 'Macropus parryi');
insert into pet (name, animal, race) values ('Raimundo', 'Sacred ibis', 'Threskionis aethiopicus');
insert into pet (name, animal, race) values ('Candace', 'Tiger snake', 'Notechis semmiannulatus');
insert into pet (name, animal, race) values ('Rozanna', 'Galapagos dove', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Bunnie', 'Long-nosed bandicoot', 'Perameles nasuta');
insert into pet (name, animal, race) values ('Jerrylee', 'White-winged black tern', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Redd', 'Leopard', 'Panthera pardus');
insert into pet (name, animal, race) values ('Leoine', 'Black curlew', 'Haematopus ater');
insert into pet (name, animal, race) values ('Erny', 'Greater flamingo', 'Phoenicopterus ruber');
insert into pet (name, animal, race) values ('Claretta', 'Rainbow lory', 'Trichoglossus haematodus moluccanus');
insert into pet (name, animal, race) values ('Genni', 'Common raccoon', 'Procyon lotor');
insert into pet (name, animal, race) values ('Kile', 'Armadillo, seven-banded', 'Dasypus septemcincus');
insert into pet (name, animal, race) values ('Blair', 'Vulture, griffon', 'Gyps fulvus');
insert into pet (name, animal, race) values ('Becka', 'Giant armadillo', 'Priodontes maximus');
insert into pet (name, animal, race) values ('Stillman', 'Common wombat', 'Vombatus ursinus');
insert into pet (name, animal, race) values ('Brina', 'Red-billed hornbill', 'Tockus erythrorhyncus');
insert into pet (name, animal, race) values ('Mellisa', 'Pied crow', 'Corvus albus');
insert into pet (name, animal, race) values ('Ade', 'Swamp deer', 'Cervus duvauceli');
insert into pet (name, animal, race) values ('Leticia', 'Polar bear', 'Ursus maritimus');
insert into pet (name, animal, race) values ('Valma', 'Deer, red', 'Cervus elaphus');
insert into pet (name, animal, race) values ('Chloris', 'African wild cat', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Mitch', 'Red lava crab', 'Graspus graspus');
insert into pet (name, animal, race) values ('Northrop', 'Beaver, eurasian', 'Castor fiber');
insert into pet (name, animal, race) values ('Fayre', 'Dove, galapagos', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Wrennie', 'Kangaroo, western grey', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Lyndsey', 'Red brocket', 'Mazama americana');
insert into pet (name, animal, race) values ('Taylor', 'Grebe, little', 'Tachybaptus ruficollis');
insert into pet (name, animal, race) values ('Sebastian', 'Toddy cat', 'Paradoxurus hermaphroditus');
insert into pet (name, animal, race) values ('Catlee', 'Common brushtail possum', 'Trichosurus vulpecula');
insert into pet (name, animal, race) values ('Randi', 'Owl, white-browed', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Ennis', 'Woodrat (unidentified)', 'Neotoma sp.');
insert into pet (name, animal, race) values ('Phylis', 'Blacksmith plover', 'Vanellus armatus');
insert into pet (name, animal, race) values ('Adda', 'Cardinal, red-capped', 'Paroaria gularis');
insert into pet (name, animal, race) values ('Gabbi', 'Crane, black-crowned', 'Balearica pavonina');
insert into pet (name, animal, race) values ('Abby', 'Eleven-banded armadillo (unidentified)', 'Cabassous sp.');
insert into pet (name, animal, race) values ('Brenn', 'Gray heron', 'Ardea cinerea');
insert into pet (name, animal, race) values ('Mirabelle', 'Red brocket', 'Mazama americana');
insert into pet (name, animal, race) values ('Dottie', 'Crocodile, nile', 'Crocodylus niloticus');
insert into pet (name, animal, race) values ('Lenna', 'Rhinoceros, black', 'Diceros bicornis');
insert into pet (name, animal, race) values ('Marissa', 'Red-billed tropic bird', 'Phaethon aethereus');
insert into pet (name, animal, race) values ('Jeramie', 'Fisher', 'Martes pennanti');
insert into pet (name, animal, race) values ('Sascha', 'Cormorant, pied', 'Phalacrocorax varius');
insert into pet (name, animal, race) values ('Theodosia', 'Raccoon, common', 'Procyon lotor');
insert into pet (name, animal, race) values ('Rockie', 'Squirrel, uinta ground', 'Spermophilus armatus');
insert into pet (name, animal, race) values ('Gilles', 'Stork, openbill', 'Anastomus oscitans');
insert into pet (name, animal, race) values ('Rhona', 'Dik, kirk''s dik', 'Madoqua kirkii');
insert into pet (name, animal, race) values ('Merill', 'Hyena, spotted', 'Crocuta crocuta');
insert into pet (name, animal, race) values ('Rodie', 'Monster, gila', 'Heloderma horridum');
insert into pet (name, animal, race) values ('Rudiger', 'Black rhinoceros', 'Diceros bicornis');
insert into pet (name, animal, race) values ('Ragnar', 'Madagascar hawk owl', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Eddy', 'Elephant, african', 'Loxodonta africana');
insert into pet (name, animal, race) values ('Filide', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Dot', 'Bee-eater, nubian', 'Merops nubicus');
insert into pet (name, animal, race) values ('Nikaniki', 'Brown and yellow marshbird', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Viviana', 'Common rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Gregg', 'Pademelon, red-legged', 'Thylogale stigmatica');
insert into pet (name, animal, race) values ('Yolanda', 'Caracal', 'Felis caracal');
insert into pet (name, animal, race) values ('Kellen', 'Common wombat', 'Vombatus ursinus');
insert into pet (name, animal, race) values ('Penny', 'Heron, gray', 'Ardea cinerea');
insert into pet (name, animal, race) values ('Justus', 'Quail, gambel''s', 'Callipepla gambelii');
insert into pet (name, animal, race) values ('Harrison', 'Mule deer', 'Odocoileus hemionus');
insert into pet (name, animal, race) values ('Georgeanna', 'Chilean flamingo', 'Phoenicopterus chilensis');
insert into pet (name, animal, race) values ('Urbanus', 'Eurasian red squirrel', 'Sciurus vulgaris');
insert into pet (name, animal, race) values ('Christabel', 'Hanuman langur', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Mirna', 'Goat, mountain', 'Oreamnos americanus');
insert into pet (name, animal, race) values ('Kalli', 'Mockingbird, galapagos', 'Nesomimus trifasciatus');
insert into pet (name, animal, race) values ('Joyan', 'African polecat', 'Ictonyx striatus');
insert into pet (name, animal, race) values ('Benny', 'Salmon pink bird eater tarantula', 'Lasiodora parahybana');
insert into pet (name, animal, race) values ('Homerus', 'Tern, arctic', 'Sterna paradisaea');
insert into pet (name, animal, race) values ('Clareta', 'Grenadier, purple', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Brianne', 'Gull, lava', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Charmine', 'Camel, dromedary', 'Camelus dromedarius');
insert into pet (name, animal, race) values ('Tome', 'Russian dragonfly', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Cecilia', 'Spoonbill, european', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Corrinne', 'Tortoise, galapagos', 'Geochelone elephantopus');
insert into pet (name, animal, race) values ('Kathe', 'Marine iguana', 'Amblyrhynchus cristatus');
insert into pet (name, animal, race) values ('Teresina', 'Lizard (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Eilis', 'Gerbil (unidentified)', 'Gerbillus sp.');
insert into pet (name, animal, race) values ('Ginger', 'Crane, sarus', 'Grus antigone');
insert into pet (name, animal, race) values ('Tito', 'Two-toed sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Durand', 'Tailless tenrec', 'Tenrec ecaudatus');
insert into pet (name, animal, race) values ('Leroy', 'Squirrel, malabar', 'Ratufa indica');
insert into pet (name, animal, race) values ('Shel', 'Elegant crested tinamou', 'Eudromia elegans');
insert into pet (name, animal, race) values ('Dodie', 'Pampa gray fox', 'Pseudalopex gymnocercus');
insert into pet (name, animal, race) values ('Randi', 'Sloth, hoffman''s', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Derry', 'Black-fronted bulbul', 'Pycnonotus nigricans');
insert into pet (name, animal, race) values ('Rees', 'Grenadier, purple', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Freeman', 'Galapagos dove', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Camey', 'Red-legged pademelon', 'Thylogale stigmatica');
insert into pet (name, animal, race) values ('Jodie', 'Legaan, Monitor (unidentified)', 'Varanus sp.');
insert into pet (name, animal, race) values ('Tynan', 'Giant heron', 'Ardea golieth');
insert into pet (name, animal, race) values ('Toby', 'Colobus, black and white', 'Colobus guerza');
insert into pet (name, animal, race) values ('Randee', 'Mourning collared dove', 'Streptopelia decipiens');
insert into pet (name, animal, race) values ('Klara', 'Macaque, rhesus', 'Macaca mulatta');
insert into pet (name, animal, race) values ('Rachel', 'Lizard, collared', 'Crotaphytus collaris');
insert into pet (name, animal, race) values ('Ailsun', 'Eagle owl (unidentified)', 'Bubo sp.');
insert into pet (name, animal, race) values ('Kakalina', 'Waved albatross', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Gert', 'Common genet', 'Genetta genetta');
insert into pet (name, animal, race) values ('Marie-jeanne', 'Barbet, black-collared', 'Lybius torquatus');
insert into pet (name, animal, race) values ('Siusan', 'Nubian bee-eater', 'Merops nubicus');
insert into pet (name, animal, race) values ('Jeri', 'Gorilla, western lowland', 'Gorilla gorilla');
insert into pet (name, animal, race) values ('Hortense', 'Skunk, western spotted', 'Spilogale gracilis');
insert into pet (name, animal, race) values ('Rufus', 'Lion, south american sea', 'Otaria flavescens');
insert into pet (name, animal, race) values ('Karry', 'Bear, grizzly', 'Ursus arctos');
insert into pet (name, animal, race) values ('Remy', 'Asian elephant', 'Elephas maximus bengalensis');
insert into pet (name, animal, race) values ('Idelle', 'Tern, white-winged black', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Tucker', 'South American puma', 'Felis concolor');
insert into pet (name, animal, race) values ('Filippa', 'Desert kangaroo rat', 'Dipodomys deserti');
insert into pet (name, animal, race) values ('Gradeigh', 'Mississippi alligator', 'Alligator mississippiensis');
insert into pet (name, animal, race) values ('Rozele', 'Bulbul, black-eyed', 'Pycnonotus barbatus');
insert into pet (name, animal, race) values ('Bertie', 'Tawny frogmouth', 'Podargus strigoides');
insert into pet (name, animal, race) values ('Noah', 'Canadian tiger swallowtail butterfly', 'Papilio canadensis');
insert into pet (name, animal, race) values ('Yvonne', 'Robin, kalahari scrub', 'Certotrichas paena');
insert into pet (name, animal, race) values ('Hermon', 'Spoonbill, white', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Lidia', 'Common seal', 'Phoca vitulina');
insert into pet (name, animal, race) values ('Dottie', 'Olive baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Sharl', 'Blue peacock', 'Pavo cristatus');
insert into pet (name, animal, race) values ('Gayler', 'Red-winged blackbird', 'Agelaius phoeniceus');
insert into pet (name, animal, race) values ('Rosella', 'Cobra (unidentified)', 'Naja sp.');
insert into pet (name, animal, race) values ('Selestina', 'Polar bear', 'Ursus maritimus');
insert into pet (name, animal, race) values ('Misti', 'Cow, scottish highland', 'Bos taurus');
insert into pet (name, animal, race) values ('Carmine', 'Common long-nosed armadillo', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Teriann', 'European wild cat', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Eula', 'Owl, great horned', 'Bubo virginianus');
insert into pet (name, animal, race) values ('Eachelle', 'Mongoose, eastern dwarf', 'Helogale undulata');
insert into pet (name, animal, race) values ('Stafani', 'Buttermilk snake', 'Coluber constrictor');
insert into pet (name, animal, race) values ('Gaelan', 'Tasmanian devil', 'Sarcophilus harrisii');
insert into pet (name, animal, race) values ('Minne', 'Wagtail, african pied', 'Motacilla aguimp');
insert into pet (name, animal, race) values ('Sophie', 'Black-throated butcher bird', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Herrick', 'Stork, openbill', 'Anastomus oscitans');
insert into pet (name, animal, race) values ('Michaela', 'Vulture, lappet-faced', 'Aegypius tracheliotus');
insert into pet (name, animal, race) values ('Jude', 'Caiman, spectacled', 'Caiman crocodilus');
insert into pet (name, animal, race) values ('Lucias', 'Screamer, crested', 'Chauna torquata');
insert into pet (name, animal, race) values ('Erskine', 'Eurasian beaver', 'Castor fiber');
insert into pet (name, animal, race) values ('Egbert', 'Greylag goose', 'Anser anser');
insert into pet (name, animal, race) values ('Mendy', 'Baleen whale', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Carson', 'Woodrat (unidentified)', 'Neotoma sp.');
insert into pet (name, animal, race) values ('Sherlock', 'Stone sheep', 'Ovis dalli stonei');
insert into pet (name, animal, race) values ('Darryl', 'Tortoise, desert', 'Gopherus agassizii');
insert into pet (name, animal, race) values ('Raquel', 'Snake, western patch-nosed', 'Salvadora hexalepis');
insert into pet (name, animal, race) values ('Engracia', 'Cape clawless otter', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Pieter', 'Black bear', 'Ursus americanus');
insert into pet (name, animal, race) values ('Kain', 'Southern hairy-nosed wombat', 'Lasiorhinus latifrons');
insert into pet (name, animal, race) values ('Leann', 'Gerbil (unidentified)', 'Gerbillus sp.');
insert into pet (name, animal, race) values ('Paulina', 'Egyptian cobra', 'Naja haje');
insert into pet (name, animal, race) values ('Carol-jean', 'Squirrel, richardson''s ground', 'Spermophilus richardsonii');
insert into pet (name, animal, race) values ('Bobbee', 'Long-billed cockatoo', 'Cacatua tenuirostris');
insert into pet (name, animal, race) values ('Aindrea', 'Skimmer, four-spotted', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Ellie', 'White stork', 'Ciconia ciconia');
insert into pet (name, animal, race) values ('Mathias', 'Bush dog', 'Speothos vanaticus');
insert into pet (name, animal, race) values ('Tana', 'Heron, yellow-crowned night', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Adriane', 'Olive baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Maurine', 'Squirrel, arctic ground', 'Spermophilus parryii');
insert into pet (name, animal, race) values ('Sascha', 'Buffalo, wild water', 'Bubalus arnee');
insert into pet (name, animal, race) values ('Chrisy', 'Red-breasted nuthatch', 'Sitta canadensis');
insert into pet (name, animal, race) values ('Sallie', 'Goose, snow', 'Anser caerulescens');
insert into pet (name, animal, race) values ('Irwin', 'Brazilian otter', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Saba', 'Albatross, galapagos', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Garold', 'Western palm tanager (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Molly', 'Monkey, black spider', 'Ateles paniscus');
insert into pet (name, animal, race) values ('Daniella', 'Stone sheep', 'Ovis dalli stonei');
insert into pet (name, animal, race) values ('Elayne', 'Pelican, great white', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Chuck', 'Gulls (unidentified)', 'Larus sp.');
insert into pet (name, animal, race) values ('Minnnie', 'Bennett''s wallaby', 'Macropus rufogriseus');
insert into pet (name, animal, race) values ('Francklin', 'Water legaan', 'Varanus salvator');
insert into pet (name, animal, race) values ('Henri', 'Squirrel, grey-footed', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Marquita', 'Gazelle, thomson''s', 'Gazella thompsonii');
insert into pet (name, animal, race) values ('Meggie', 'Greater sage grouse', 'Centrocercus urophasianus');
insert into pet (name, animal, race) values ('Tildie', 'King vulture', 'Sarcorhamphus papa');
insert into pet (name, animal, race) values ('Karlis', 'Rhea, greater', 'Rhea americana');
insert into pet (name, animal, race) values ('Bord', 'Long-tailed jaeger', 'Stercorarius longicausus');
insert into pet (name, animal, race) values ('Pavlov', 'Lion, california sea', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Margareta', 'Blackish oystercatcher', 'Haematopus ater');
insert into pet (name, animal, race) values ('Charo', 'Greylag goose', 'Anser anser');
insert into pet (name, animal, race) values ('Dallon', 'Cormorant, king', 'Phalacrocorax albiventer');
insert into pet (name, animal, race) values ('Kora', 'Tayra', 'Eira barbata');
insert into pet (name, animal, race) values ('Northrup', 'Buffalo, wild water', 'Bubalus arnee');
insert into pet (name, animal, race) values ('Rodi', 'Tenrec, tailless', 'Tenrec ecaudatus');
insert into pet (name, animal, race) values ('Katina', 'Gazelle, thomson''s', 'Gazella thompsonii');
insert into pet (name, animal, race) values ('Jerad', 'Phalarope, northern', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Alida', 'Bee-eater, white-fronted', 'Merops bullockoides');
insert into pet (name, animal, race) values ('Darryl', 'White-faced whistling duck', 'Dendrocygna viduata');
insert into pet (name, animal, race) values ('Trescha', 'Spotted wood sandpiper', 'Tringa glareola');
insert into pet (name, animal, race) values ('Mychal', 'American beaver', 'Castor canadensis');
insert into pet (name, animal, race) values ('Gisela', 'Snake-necked turtle', 'Chelodina longicollis');
insert into pet (name, animal, race) values ('Corella', 'Wambenger, red-tailed', 'Phascogale calura');
insert into pet (name, animal, race) values ('Cherry', 'Common turkey', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Helen-elizabeth', 'Bear, polar', 'Ursus maritimus');
insert into pet (name, animal, race) values ('Augustus', 'Fox, blue', 'Alopex lagopus');
insert into pet (name, animal, race) values ('Spenser', 'Egyptian goose', 'Alopochen aegyptiacus');
insert into pet (name, animal, race) values ('Laverna', 'Weaver, sociable', 'Philetairus socius');
insert into pet (name, animal, race) values ('Bail', 'Elephant, asian', 'Elephas maximus bengalensis');
insert into pet (name, animal, race) values ('Adriena', 'Indian red admiral', 'Vanessa indica');
insert into pet (name, animal, race) values ('Jolee', 'Cougar', 'Felis concolor');
insert into pet (name, animal, race) values ('Horacio', 'Chestnut weaver', 'Ploceus rubiginosus');
insert into pet (name, animal, race) values ('Wolfie', 'Yellow mongoose', 'Cynictis penicillata');
insert into pet (name, animal, race) values ('York', 'Long-tailed jaeger', 'Stercorarius longicausus');
insert into pet (name, animal, race) values ('Minetta', 'Iguana, land', 'Conolophus subcristatus');
insert into pet (name, animal, race) values ('Becky', 'Baboon, olive', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Bogart', 'Dog, black-tailed prairie', 'Cynomys ludovicianus');
insert into pet (name, animal, race) values ('Georges', 'Gonolek, burchell''s', 'Laniaurius atrococcineus');
insert into pet (name, animal, race) values ('Gillie', 'African bush squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Beaufort', 'Curlew, black', 'Haematopus ater');
insert into pet (name, animal, race) values ('Augustine', 'Jackrabbit, white-tailed', 'Lepus townsendii');
insert into pet (name, animal, race) values ('Tailor', 'Otter, oriental short-clawed', 'Aonyx cinerea');
insert into pet (name, animal, race) values ('Jamill', 'Otter, brazilian', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Rufus', 'Chimpanzee', 'Pan troglodytes');
insert into pet (name, animal, race) values ('Mella', 'Wild turkey', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Sherilyn', 'Lemur, brown', 'Lemur fulvus');
insert into pet (name, animal, race) values ('Marlane', 'Rufous tree pie', 'Dendrocitta vagabunda');
insert into pet (name, animal, race) values ('Lindi', 'Red squirrel', 'Tamiasciurus hudsonicus');
insert into pet (name, animal, race) values ('Eimile', 'Eastern quoll', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Pepe', 'Snake, green vine', 'Oxybelis fulgidus');
insert into pet (name, animal, race) values ('Jorrie', 'American beaver', 'Castor canadensis');
insert into pet (name, animal, race) values ('Margarethe', 'Seal, common', 'Phoca vitulina');
insert into pet (name, animal, race) values ('Darya', 'Chickadee, black-capped', 'Parus atricapillus');
insert into pet (name, animal, race) values ('Eustace', 'Sulfur-crested cockatoo', 'Cacatua galerita');
insert into pet (name, animal, race) values ('Ibby', 'Screamer, southern', 'Chauna torquata');
insert into pet (name, animal, race) values ('Maynard', 'Boat-billed heron', 'Cochlearius cochlearius');
insert into pet (name, animal, race) values ('Fionna', 'Jackal, silver-backed', 'Canis mesomelas');
insert into pet (name, animal, race) values ('Thedric', 'Gull, herring', 'unavailable');
insert into pet (name, animal, race) values ('Shaine', 'Numbat', 'Myrmecobius fasciatus');
insert into pet (name, animal, race) values ('Desi', 'Black and white colobus', 'Colobus guerza');
insert into pet (name, animal, race) values ('Chickie', 'Hyena, spotted', 'Crocuta crocuta');
insert into pet (name, animal, race) values ('Harriet', 'Curve-billed thrasher', 'Toxostoma curvirostre');
insert into pet (name, animal, race) values ('Haleigh', 'Armadillo, common long-nosed', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Rebbecca', 'Stork, yellow-billed', 'Mycteria ibis');
insert into pet (name, animal, race) values ('Chrissie', 'Spoonbill, european', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Brewster', 'Beaver, american', 'Castor canadensis');
insert into pet (name, animal, race) values ('Emmett', 'Goose, canada', 'Branta canadensis');
insert into pet (name, animal, race) values ('Langston', 'Striated heron', 'Butorides striatus');
insert into pet (name, animal, race) values ('Gilly', 'Numbat', 'Myrmecobius fasciatus');
insert into pet (name, animal, race) values ('Dorine', 'Smith''s bush squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Sauveur', 'Heron, green', 'Butorides striatus');
insert into pet (name, animal, race) values ('Riley', 'Civet (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Zeke', 'Black-crowned night heron', 'Nycticorax nycticorax');
insert into pet (name, animal, race) values ('Alie', 'Greater blue-eared starling', 'Lamprotornis chalybaeus');
insert into pet (name, animal, race) values ('Shirlee', 'Cook''s tree boa', 'Corallus hortulanus cooki');
insert into pet (name, animal, race) values ('Rosmunda', 'Canadian river otter', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Alicia', 'Long-finned pilot whale', 'Globicephala melas');
insert into pet (name, animal, race) values ('Dorette', 'South American puma', 'Felis concolor');
insert into pet (name, animal, race) values ('Camel', 'Blacksmith plover', 'Vanellus armatus');
insert into pet (name, animal, race) values ('Wendy', 'Koala', 'Phascolarctos cinereus');
insert into pet (name, animal, race) values ('Olympe', 'Black curlew', 'Haematopus ater');
insert into pet (name, animal, race) values ('Lorain', 'Baboon, gelada', 'Theropithecus gelada');
insert into pet (name, animal, race) values ('Rebekkah', 'Plover, three-banded', 'Charadrius tricollaris');
insert into pet (name, animal, race) values ('Pattie', 'Bee-eater, carmine', 'Merops nubicus');
insert into pet (name, animal, race) values ('Pauli', 'Black-tailed prairie dog', 'Cynomys ludovicianus');
insert into pet (name, animal, race) values ('Pris', 'Lourie, grey', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Wernher', 'Lourie, grey', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Mauricio', 'Iguana, land', 'Conolophus subcristatus');
insert into pet (name, animal, race) values ('Cristobal', 'Bat, madagascar fruit', 'Pteropus rufus');
insert into pet (name, animal, race) values ('Grissel', 'Nyala', 'Tragelaphus angasi');
insert into pet (name, animal, race) values ('Jamil', 'Butterfly (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Mari', 'Cape starling', 'Lamprotornis nitens');
insert into pet (name, animal, race) values ('Liva', 'Snowy sheathbill', 'Chionis alba');
insert into pet (name, animal, race) values ('Abbi', 'Griffon vulture', 'Gyps fulvus');
insert into pet (name, animal, race) values ('Martica', 'Little heron', 'Butorides striatus');
insert into pet (name, animal, race) values ('Irma', 'Phalarope, red-necked', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Humfrey', 'Common wombat', 'Vombatus ursinus');
insert into pet (name, animal, race) values ('Magdaia', 'Raccoon, common', 'Procyon lotor');
insert into pet (name, animal, race) values ('Ula', 'Indian mynah', 'Acridotheres tristis');
insert into pet (name, animal, race) values ('Arabelle', 'Genet, common', 'Genetta genetta');
insert into pet (name, animal, race) values ('Tuckie', 'Ox, musk', 'Ovibos moschatus');
insert into pet (name, animal, race) values ('Pablo', 'Gambel''s quail', 'Callipepla gambelii');
insert into pet (name, animal, race) values ('Rock', 'Western lowland gorilla', 'Gorilla gorilla');
insert into pet (name, animal, race) values ('Freida', 'Greylag goose', 'Anser anser');
insert into pet (name, animal, race) values ('Jenny', 'Striped skunk', 'Mephitis mephitis');
insert into pet (name, animal, race) values ('Neville', 'Two-toed tree sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Leonard', 'Shelduck, common', 'Tadorna tadorna');
insert into pet (name, animal, race) values ('Jennette', 'Possum, western pygmy', 'Cercatetus concinnus');
insert into pet (name, animal, race) values ('Pepillo', 'Tern, arctic', 'Sterna paradisaea');
insert into pet (name, animal, race) values ('Minni', 'Galapagos mockingbird', 'Nesomimus trifasciatus');
insert into pet (name, animal, race) values ('Connie', 'Shark, blue', 'Prionace glauca');
insert into pet (name, animal, race) values ('Alane', 'Tortoise, indian star', 'Geochelone elegans');
insert into pet (name, animal, race) values ('Karrie', 'White-winged tern', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Rudie', 'Black-cheeked waxbill', 'Estrilda erythronotos');
insert into pet (name, animal, race) values ('Corrinne', 'Tokay gecko', 'Gekko gecko');
insert into pet (name, animal, race) values ('Tito', 'Squirrel, european red', 'Sciurus vulgaris');
insert into pet (name, animal, race) values ('Rorie', 'Goldeneye, barrows', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Marcelia', 'Southern black-backed gull', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Prudence', 'Gull, swallow-tail', 'Creagrus furcatus');
insert into pet (name, animal, race) values ('Dasie', 'Tsessebe', 'Damaliscus lunatus');
insert into pet (name, animal, race) values ('Cortney', 'Sloth, pale-throated three-toed', 'Bradypus tridactylus');
insert into pet (name, animal, race) values ('Garnet', 'Phalarope, red-necked', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Josy', 'Wagtail, african pied', 'Motacilla aguimp');
insert into pet (name, animal, race) values ('Delly', 'Cape raven', 'Corvus albicollis');
insert into pet (name, animal, race) values ('Dynah', 'Red kangaroo', 'Macropus rufus');
insert into pet (name, animal, race) values ('Gun', 'Eagle, golden', 'Aquila chrysaetos');
insert into pet (name, animal, race) values ('Meghann', 'Lory, rainbow', 'Trichoglossus haematodus moluccanus');
insert into pet (name, animal, race) values ('Henrietta', 'European beaver', 'Castor fiber');
insert into pet (name, animal, race) values ('De witt', 'Square-lipped rhinoceros', 'Ceratotherium simum');
insert into pet (name, animal, race) values ('Orion', 'Godwit, hudsonian', 'Limosa haemastica');
insert into pet (name, animal, race) values ('Nicolette', 'Springbok', 'Antidorcas marsupialis');
insert into pet (name, animal, race) values ('Binni', 'Yellow-rumped siskin', 'Carduelis uropygialis');
insert into pet (name, animal, race) values ('Annalee', 'Gecko (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Randie', 'African clawless otter', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Brian', 'Spotted-tailed quoll', 'Dasyurus maculatus');
insert into pet (name, animal, race) values ('Bobbye', 'Black curlew', 'Haematopus ater');
insert into pet (name, animal, race) values ('Nelie', 'Cormorant, little', 'Phalacrocorax niger');
insert into pet (name, animal, race) values ('Jodi', 'Dark-winged trumpeter', 'Psophia viridis');
insert into pet (name, animal, race) values ('Charmian', 'Western grey kangaroo', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Antonella', 'Gray duiker', 'Sylvicapra grimma');
insert into pet (name, animal, race) values ('Burty', 'Meerkat, red', 'Cynictis penicillata');
insert into pet (name, animal, race) values ('Ardelis', 'South American meadowlark (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Andonis', 'Meerkat', 'Suricata suricatta');
insert into pet (name, animal, race) values ('Chad', 'Dove, little brown', 'Streptopelia senegalensis');
insert into pet (name, animal, race) values ('Lorant', 'American beaver', 'Castor canadensis');
insert into pet (name, animal, race) values ('Esma', 'Sheep, red', 'Ovis ammon');
insert into pet (name, animal, race) values ('Ennis', 'Vine snake (unidentified)', 'Oxybelis sp.');
insert into pet (name, animal, race) values ('Gabe', 'Whale, southern right', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Kassie', 'Kangaroo, jungle', 'Macropus agilis');
insert into pet (name, animal, race) values ('Barbabas', 'Flamingo, chilean', 'Phoenicopterus chilensis');
insert into pet (name, animal, race) values ('Natalee', 'Desert tortoise', 'Gopherus agassizii');
insert into pet (name, animal, race) values ('Northrop', 'Lemur, brown', 'Lemur fulvus');
insert into pet (name, animal, race) values ('Cary', 'Eastern boa constrictor', 'Acrantophis madagascariensis');
insert into pet (name, animal, race) values ('Ram', 'Brown hyena', 'Hyaena brunnea');
insert into pet (name, animal, race) values ('Aubree', 'Herring gull', 'unavailable');
insert into pet (name, animal, race) values ('Velvet', 'Starling, cape', 'Lamprotornis nitens');
insert into pet (name, animal, race) values ('Fons', 'Fox, north american red', 'Vulpes vulpes');
insert into pet (name, animal, race) values ('Genia', 'Albatross, galapagos', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Elspeth', 'Snake, green vine', 'Oxybelis fulgidus');
insert into pet (name, animal, race) values ('Chere', 'Wapiti, elk,', 'Cervus canadensis');
insert into pet (name, animal, race) values ('Jeniece', 'Waterbuck, defassa', 'Kobus defassa');
insert into pet (name, animal, race) values ('Krishna', 'Sloth bear', 'Melursus ursinus');
insert into pet (name, animal, race) values ('Adaline', 'Tokay gecko', 'Gekko gecko');
insert into pet (name, animal, race) values ('Bil', 'Common turkey', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Kristy', 'Jackal, golden', 'Canis aureus');
insert into pet (name, animal, race) values ('Tyler', 'Wapiti, elk,', 'Cervus canadensis');
insert into pet (name, animal, race) values ('Etta', 'Skunk, striped', 'Mephitis mephitis');
insert into pet (name, animal, race) values ('Garland', 'Weaver, white-browed sparrow', 'Plocepasser mahali');
insert into pet (name, animal, race) values ('Reina', 'Deer, black-tailed', 'Odocoileus hemionus');
insert into pet (name, animal, race) values ('Myrwyn', 'Common mynah', 'Acridotheres tristis');
insert into pet (name, animal, race) values ('Fawnia', 'Black kite', 'Milvus migrans');
insert into pet (name, animal, race) values ('Sebastiano', 'Goose, egyptian', 'Alopochen aegyptiacus');
insert into pet (name, animal, race) values ('Bernadette', 'Bat-eared fox', 'Otocyon megalotis');
insert into pet (name, animal, race) values ('Buckie', 'Black-capped chickadee', 'Parus atricapillus');
insert into pet (name, animal, race) values ('Fern', 'Javan gold-spotted mongoose', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Aurel', 'Striped hyena', 'Hyaena hyaena');
insert into pet (name, animal, race) values ('Arabelle', 'Native cat', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Ignacius', 'Mongoose, banded', 'Mungos mungo');
insert into pet (name, animal, race) values ('Rebbecca', 'Kirk''s dik dik', 'Madoqua kirkii');
insert into pet (name, animal, race) values ('Sansone', 'Bird, pied butcher', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Teriann', 'Egyptian viper', 'Naja haje');
insert into pet (name, animal, race) values ('Andrej', 'Racer, american', 'Coluber constrictor');
insert into pet (name, animal, race) values ('Aloise', 'Hornbill, southern ground', 'Bucorvus leadbeateri');
insert into pet (name, animal, race) values ('Ode', 'Lava gull', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Kessiah', 'Cardinal, red-capped', 'Paroaria gularis');
insert into pet (name, animal, race) values ('Tedda', 'Red-billed buffalo weaver', 'Bubalornis niger');
insert into pet (name, animal, race) values ('Trevar', 'Brazilian otter', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Jeff', 'Brown and yellow marshbird', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Jeane', 'Mallard', 'Anas platyrhynchos');
insert into pet (name, animal, race) values ('Nollie', 'Cat, long-tailed spotted', 'Felis wiedi or Leopardus weidi');
insert into pet (name, animal, race) values ('Alessandro', 'Badger, european', 'Meles meles');
insert into pet (name, animal, race) values ('Killie', 'Arctic hare', 'Lepus arcticus');
insert into pet (name, animal, race) values ('Nikolas', 'Quoll, spotted-tailed', 'Dasyurus maculatus');
insert into pet (name, animal, race) values ('Zoe', 'Laughing dove', 'Streptopelia senegalensis');
insert into pet (name, animal, race) values ('Emmerich', 'Falcon, peregrine', 'Falco peregrinus');
insert into pet (name, animal, race) values ('Kathy', 'Black-capped chickadee', 'Parus atricapillus');
insert into pet (name, animal, race) values ('Estelle', 'Jaguarundi', 'Felis yagouaroundi');
insert into pet (name, animal, race) values ('Giavani', 'Egyptian vulture', 'Neophron percnopterus');
insert into pet (name, animal, race) values ('Leupold', 'Barbet, crested', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Anselm', 'Common zorro', 'Dusicyon thous');
insert into pet (name, animal, race) values ('Gabi', 'Wallaby, agile', 'Macropus agilis');
insert into pet (name, animal, race) values ('Boone', 'Cape wild cat', 'Felis libyca');
insert into pet (name, animal, race) values ('Ulrick', 'Southern right whale', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Rianon', 'White-browed owl', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Biddie', 'Otter, small-clawed', 'Aonyx cinerea');
insert into pet (name, animal, race) values ('Rosella', 'Killer whale', 'Orcinus orca');
insert into pet (name, animal, race) values ('Shay', 'Snowy egret', 'Egretta thula');
insert into pet (name, animal, race) values ('Yolanthe', 'Dusky gull', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Britteny', 'Barbet, crested', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Byron', 'Wild turkey', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Gertrudis', 'Vulture, white-rumped', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('Stanton', 'Secretary bird', 'Sagittarius serpentarius');
insert into pet (name, animal, race) values ('Claudine', 'Blue waxbill', 'Uraeginthus angolensis');
insert into pet (name, animal, race) values ('Valeda', 'Red howler monkey', 'Alouatta seniculus');
insert into pet (name, animal, race) values ('Virgie', 'Red-billed hornbill', 'Tockus erythrorhyncus');
insert into pet (name, animal, race) values ('Winnie', 'Common nighthawk', 'Chordeiles minor');
insert into pet (name, animal, race) values ('Elsinore', 'Blue-footed booby', 'Sula nebouxii');
insert into pet (name, animal, race) values ('Lynna', 'Ibex', 'Capra ibex');
insert into pet (name, animal, race) values ('Dane', 'Gazelle, thomson''s', 'Gazella thompsonii');
insert into pet (name, animal, race) values ('Kelby', 'Asiatic jackal', 'Canis aureus');
insert into pet (name, animal, race) values ('Carrissa', 'Stick insect', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Galen', 'Heron, giant', 'Ardea golieth');
insert into pet (name, animal, race) values ('Ardyth', 'Thomson''s gazelle', 'Gazella thompsonii');
insert into pet (name, animal, race) values ('Kellia', 'Australian sea lion', 'Neophoca cinerea');
insert into pet (name, animal, race) values ('Alain', 'Goose, cape barren', 'Cereopsis novaehollandiae');
insert into pet (name, animal, race) values ('Zed', 'Fox, crab-eating', 'Dusicyon thous');
insert into pet (name, animal, race) values ('Haze', 'Indian peacock', 'Pavo cristatus');
insert into pet (name, animal, race) values ('Norene', 'Goanna lizard', 'Varanus sp.');
insert into pet (name, animal, race) values ('Myrle', 'Lion, asian', 'Panthera leo persica');
insert into pet (name, animal, race) values ('Shandee', 'Bontebok', 'Damaliscus dorcas');
insert into pet (name, animal, race) values ('Anastasie', 'Bear, sloth', 'Melursus ursinus');
insert into pet (name, animal, race) values ('Hugues', 'Ass, asiatic wild', 'Equus hemionus');
insert into pet (name, animal, race) values ('Westleigh', 'Turtle, snake-necked', 'Chelodina longicollis');
insert into pet (name, animal, race) values ('Sim', 'Grizzly bear', 'Ursus arctos');
insert into pet (name, animal, race) values ('Wolfie', 'Coot, red-knobbed', 'Fulica cristata');
insert into pet (name, animal, race) values ('Rolfe', 'American beaver', 'Castor canadensis');
insert into pet (name, animal, race) values ('Gilli', 'Brown hyena', 'Hyaena brunnea');
insert into pet (name, animal, race) values ('Otes', 'Tortoise, radiated', 'Geochelone radiata');
insert into pet (name, animal, race) values ('Alonso', 'American beaver', 'Castor canadensis');
insert into pet (name, animal, race) values ('Barrett', 'River wallaby', 'Macropus agilis');
insert into pet (name, animal, race) values ('Jacklyn', 'Gerenuk', 'Litrocranius walleri');
insert into pet (name, animal, race) values ('Darb', 'Red-billed tropic bird', 'Phaethon aethereus');
insert into pet (name, animal, race) values ('Wallas', 'Kangaroo, eastern grey', 'Macropus giganteus');
insert into pet (name, animal, race) values ('Gaby', 'Pheasant, common', 'Phasianus colchicus');
insert into pet (name, animal, race) values ('Neron', 'Asian water dragon', 'Physignathus cocincinus');
insert into pet (name, animal, race) values ('Park', 'Saddle-billed stork', 'Ephipplorhynchus senegalensis');
insert into pet (name, animal, race) values ('Micheil', 'Bleu, red-cheeked cordon', 'Uraeginthus bengalus');
insert into pet (name, animal, race) values ('Ricki', 'Common dolphin', 'Delphinus delphis');
insert into pet (name, animal, race) values ('Darryl', 'Tamandua, southern', 'Tamandua tetradactyla');
insert into pet (name, animal, race) values ('Mellisent', 'Insect, stick', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Asher', 'Hartebeest, coke''s', 'Alcelaphus buselaphus cokii');
insert into pet (name, animal, race) values ('Clarita', 'Asian false vampire bat', 'Megaderma spasma');
insert into pet (name, animal, race) values ('Lanna', 'Possum, western pygmy', 'Cercatetus concinnus');
insert into pet (name, animal, race) values ('Chrisy', 'Blue-breasted cordon bleu', 'Uraeginthus angolensis');
insert into pet (name, animal, race) values ('Lanette', 'African lion', 'Panthera leo');
insert into pet (name, animal, race) values ('Gavin', 'Roseate cockatoo', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Emery', 'African bush squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Arielle', 'Trumpeter, dark-winged', 'Psophia viridis');
insert into pet (name, animal, race) values ('Courtney', 'Bushbaby, large-eared', 'Galago crassicaudataus');
insert into pet (name, animal, race) values ('Neile', 'Grey fox', 'Vulpes cinereoargenteus');
insert into pet (name, animal, race) values ('Sawyer', 'Owl, australian masked', 'Tyto novaehollandiae');
insert into pet (name, animal, race) values ('Ray', 'Cat, ringtail', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Deanne', 'Mexican boa', 'Boa constrictor mexicana');
insert into pet (name, animal, race) values ('Cleveland', 'Finch, common melba', 'Pytilia melba');
insert into pet (name, animal, race) values ('Roderigo', 'Russian dragonfly', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Giselbert', 'Darwin ground finch (unidentified)', 'Geospiza sp.');
insert into pet (name, animal, race) values ('Gideon', 'Tortoise, desert', 'Gopherus agassizii');
insert into pet (name, animal, race) values ('Ramsay', 'Gorilla, western lowland', 'Gorilla gorilla');
insert into pet (name, animal, race) values ('Thor', 'Mountain duck', 'Hymenolaimus malacorhynchus');
insert into pet (name, animal, race) values ('Etta', 'Bent-toed gecko', 'Cyrtodactylus louisiadensis');
insert into pet (name, animal, race) values ('Lanny', 'Siskin, pine', 'Carduelis pinus');
insert into pet (name, animal, race) values ('Antonio', 'Red lava crab', 'Graspus graspus');
insert into pet (name, animal, race) values ('Valentijn', 'Sarus crane', 'Grus antigone');
insert into pet (name, animal, race) values ('Arley', 'Lark, horned', 'Eremophila alpestris');
insert into pet (name, animal, race) values ('Frankie', 'Lizard, giant girdled', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Rik', 'Savanna baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Bel', 'Red squirrel', 'Tamiasciurus hudsonicus');
insert into pet (name, animal, race) values ('Nickey', 'Ostrich', 'Struthio camelus');
insert into pet (name, animal, race) values ('Eldon', 'Jackal, black-backed', 'Canis mesomelas');
insert into pet (name, animal, race) values ('Sheelagh', 'Two-toed sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Beale', 'Waxbill, blue', 'Uraeginthus angolensis');
insert into pet (name, animal, race) values ('Frank', 'Cobra, cape', 'Naja nivea');
insert into pet (name, animal, race) values ('Rivalee', 'Puffin, horned', 'Fratercula corniculata');
insert into pet (name, animal, race) values ('Roberta', 'Pronghorn', 'Antilocapra americana');
insert into pet (name, animal, race) values ('Darbee', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Bryan', 'Feral rock pigeon', 'Columba livia');
insert into pet (name, animal, race) values ('Harlen', 'Jaguarundi', 'Felis yagouaroundi');
insert into pet (name, animal, race) values ('Sigismond', 'Two-toed tree sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Winifred', 'Buffalo, asian water', 'Bubalus arnee');
insert into pet (name, animal, race) values ('Kaycee', 'White-throated robin', 'Irania gutteralis');
insert into pet (name, animal, race) values ('Darsie', 'Badger, american', 'Taxidea taxus');
insert into pet (name, animal, race) values ('Nicol', 'Jackrabbit, white-tailed', 'Lepus townsendii');
insert into pet (name, animal, race) values ('Veradis', 'Red-billed tropic bird', 'Phaethon aethereus');
insert into pet (name, animal, race) values ('Kristine', 'Galapagos penguin', 'Spheniscus mendiculus');
insert into pet (name, animal, race) values ('Jenny', 'Penguin, magellanic', 'Spheniscus magellanicus');
insert into pet (name, animal, race) values ('Scotti', 'Ring-tailed lemur', 'Lemur catta');
insert into pet (name, animal, race) values ('Boy', 'Beaver, north american', 'Castor canadensis');
insert into pet (name, animal, race) values ('Jen', 'Tamandua, southern', 'Tamandua tetradactyla');
insert into pet (name, animal, race) values ('Kalvin', 'Turkey, wild', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Kristien', 'Plains zebra', 'Equus burchelli');
insert into pet (name, animal, race) values ('Arluene', 'Heron, black-crowned night', 'Nycticorax nycticorax');
insert into pet (name, animal, race) values ('Thurston', 'White-tailed deer', 'Odocoilenaus virginianus');
insert into pet (name, animal, race) values ('Dominga', 'Long-tailed jaeger', 'Stercorarius longicausus');
insert into pet (name, animal, race) values ('Gerry', 'Rhea, greater', 'Rhea americana');
insert into pet (name, animal, race) values ('Maggie', 'Red-winged hawk (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Carlota', 'Emerald-spotted wood dove', 'Turtur chalcospilos');
insert into pet (name, animal, race) values ('Forrest', 'Gull, kelp', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Muriel', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Georgie', 'Zebra, plains', 'Equus burchelli');
insert into pet (name, animal, race) values ('Aluin', 'Kinkajou', 'Potos flavus');
insert into pet (name, animal, race) values ('Mattie', 'Slender-billed cockatoo', 'Cacatua tenuirostris');
insert into pet (name, animal, race) values ('Edmon', 'Roseate cockatoo', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Roberto', 'Squirrel, grey-footed', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Glyn', 'Blue-tongued lizard', 'Tiliqua scincoides');
insert into pet (name, animal, race) values ('Gianina', 'Brown antechinus', 'Antechinus flavipes');
insert into pet (name, animal, race) values ('Tanney', 'Turkey vulture', 'Cathartes aura');
insert into pet (name, animal, race) values ('Zeke', 'Skunk, western spotted', 'Spilogale gracilis');
insert into pet (name, animal, race) values ('Carmelita', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Maureen', 'Sandgrouse, yellow-throated', 'Pterocles gutturalis');
insert into pet (name, animal, race) values ('Feodor', 'Chameleon (unidentified)', 'Chamaelo sp.');
insert into pet (name, animal, race) values ('Rozamond', 'Kingfisher, malachite', 'Corythornis cristata');
insert into pet (name, animal, race) values ('Cherida', 'Indian peacock', 'Pavo cristatus');
insert into pet (name, animal, race) values ('Cull', 'Great cormorant', 'Phalacrocorax carbo');
insert into pet (name, animal, race) values ('Milty', 'European shelduck', 'Tadorna tadorna');
insert into pet (name, animal, race) values ('Ricca', 'Goose, andean', 'Chloephaga melanoptera');
insert into pet (name, animal, race) values ('Tedd', 'Gull, kelp', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Melodee', 'Rattlesnake, dusky', 'Crotalus triseriatus');
insert into pet (name, animal, race) values ('Wolfy', 'Hyena, brown', 'Hyaena brunnea');
insert into pet (name, animal, race) values ('Alphonso', 'Kaffir cat', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Alvis', 'Otter, african clawless', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Gertrudis', 'Pine snake (unidentified)', 'Pituophis melanaleucus');
insert into pet (name, animal, race) values ('Lilyan', 'Macaw, blue and yellow', 'Ara ararauna');
insert into pet (name, animal, race) values ('Skipton', 'Common duiker', 'Sylvicapra grimma');
insert into pet (name, animal, race) values ('Lorianna', 'Bengal vulture', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('Cosette', 'Azara''s zorro', 'Pseudalopex gymnocercus');
insert into pet (name, animal, race) values ('Zackariah', 'Asian red fox', 'Vulpes vulpes');
insert into pet (name, animal, race) values ('Letizia', 'Red brocket', 'Mazama americana');
insert into pet (name, animal, race) values ('Lacey', 'Lion, asian', 'Panthera leo persica');
insert into pet (name, animal, race) values ('Dante', 'Viper, egyptian', 'Naja haje');
insert into pet (name, animal, race) values ('Muffin', 'Carpet python', 'Morelia spilotes variegata');
insert into pet (name, animal, race) values ('Putnam', 'Common long-nosed armadillo', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Tab', 'Magistrate black colobus', 'Colobus guerza');
insert into pet (name, animal, race) values ('Marleen', 'American black bear', 'Ursus americanus');
insert into pet (name, animal, race) values ('Giacobo', 'Mongoose, small indian', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Tana', 'Monkey, red howler', 'Alouatta seniculus');
insert into pet (name, animal, race) values ('Cosetta', 'Hartebeest, coke''s', 'Alcelaphus buselaphus cokii');
insert into pet (name, animal, race) values ('Beverlie', 'Greylag goose', 'Anser anser');
insert into pet (name, animal, race) values ('Arney', 'Blue waxbill', 'Uraeginthus angolensis');
insert into pet (name, animal, race) values ('Kalina', 'Roan antelope', 'Hippotragus equinus');
insert into pet (name, animal, race) values ('Benoit', 'Caracara (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Serene', 'Defassa waterbuck', 'Kobus defassa');
insert into pet (name, animal, race) values ('Cale', 'Madagascar fruit bat', 'Pteropus rufus');
insert into pet (name, animal, race) values ('Irina', 'Andean goose', 'Chloephaga melanoptera');
insert into pet (name, animal, race) values ('Harland', 'Bee-eater, nubian', 'Merops nubicus');
insert into pet (name, animal, race) values ('Deina', 'Goliath heron', 'Ardea golieth');
insert into pet (name, animal, race) values ('Steffane', 'Southern screamer', 'Chauna torquata');
insert into pet (name, animal, race) values ('Nathanael', 'Mexican boa', 'Boa constrictor mexicana');
insert into pet (name, animal, race) values ('Radcliffe', 'Spurfowl, yellow-necked', 'Francolinus leucoscepus');
insert into pet (name, animal, race) values ('Federica', 'Hornbill, southern ground', 'Bucorvus leadbeateri');
insert into pet (name, animal, race) values ('Danell', 'Rat, arboral spiny', 'Echimys chrysurus');
insert into pet (name, animal, race) values ('Garvey', 'Squirrel, uinta ground', 'Spermophilus armatus');
insert into pet (name, animal, race) values ('Gordon', 'Crake, african black', 'Limnocorax flavirostra');
insert into pet (name, animal, race) values ('Aprilette', 'Lizard (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Archambault', 'Steenbuck', 'Raphicerus campestris');
insert into pet (name, animal, race) values ('Bartie', 'Boa, malagasy ground', 'Acrantophis madagascariensis');
insert into pet (name, animal, race) values ('Ellette', 'Komodo dragon', 'Varanus komodensis');
insert into pet (name, animal, race) values ('Clayton', 'Steenbuck', 'Raphicerus campestris');
insert into pet (name, animal, race) values ('Barrie', 'Jabiru stork', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Blanca', 'Kangaroo, jungle', 'Macropus agilis');
insert into pet (name, animal, race) values ('Giles', 'Indian red admiral', 'Vanessa indica');
insert into pet (name, animal, race) values ('Ringo', 'Common zebra', 'Equus burchelli');
insert into pet (name, animal, race) values ('Danika', 'Sulfur-crested cockatoo', 'Cacatua galerita');
insert into pet (name, animal, race) values ('Johnath', 'Civet, common palm', 'Paradoxurus hermaphroditus');
insert into pet (name, animal, race) values ('Codee', 'Arboral spiny rat', 'Echimys chrysurus');
insert into pet (name, animal, race) values ('Erhart', 'Brown brocket', 'Mazama gouazoubira');
insert into pet (name, animal, race) values ('Broderick', 'Waved albatross', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Kellie', 'Field flicker', 'Colaptes campestroides');
insert into pet (name, animal, race) values ('Cher', 'White-fronted capuchin', 'Cebus albifrons');
insert into pet (name, animal, race) values ('Marysa', 'Robin, white-throated', 'Irania gutteralis');
insert into pet (name, animal, race) values ('Ezra', 'White-throated kingfisher', 'Halcyon smyrnesis');
insert into pet (name, animal, race) values ('Petr', 'Brindled gnu', 'Connochaetus taurinus');
insert into pet (name, animal, race) values ('Cyb', 'Tyrant flycatcher', 'Myiarchus tuberculifer');
insert into pet (name, animal, race) values ('Renata', 'Sungazer, yellow-brown', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Elspeth', 'Gerbil (unidentified)', 'Gerbillus sp.');
insert into pet (name, animal, race) values ('Tim', 'Paradoxure', 'Paradoxurus hermaphroditus');
insert into pet (name, animal, race) values ('Griffie', 'Screamer, crested', 'Chauna torquata');
insert into pet (name, animal, race) values ('Eolande', 'Sportive lemur', 'Lepilemur rufescens');
insert into pet (name, animal, race) values ('Angele', 'Rock dove', 'Columba livia');
insert into pet (name, animal, race) values ('Marianne', 'Wild boar', 'Sus scrofa');
insert into pet (name, animal, race) values ('Stacey', 'Sungazer, yellow-brown', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Vachel', 'Stanley bustard', 'Neotis denhami');
insert into pet (name, animal, race) values ('Valentine', 'Eastern fox squirrel', 'Sciurus niger');
insert into pet (name, animal, race) values ('Carin', 'Cockatoo, red-tailed', 'Calyptorhynchus magnificus');
insert into pet (name, animal, race) values ('Panchito', 'Marine iguana', 'Amblyrhynchus cristatus');
insert into pet (name, animal, race) values ('Isaac', 'European beaver', 'Castor fiber');
insert into pet (name, animal, race) values ('Morissa', 'Cardinal, red-capped', 'Paroaria gularis');
insert into pet (name, animal, race) values ('Ansel', 'Baleen whale', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Gayle', 'River wallaby', 'Macropus agilis');
insert into pet (name, animal, race) values ('Carlin', 'Arctic lemming', 'Dicrostonyx groenlandicus');
insert into pet (name, animal, race) values ('Olivette', 'Sidewinder', 'Crotalus cerastes');
insert into pet (name, animal, race) values ('Chaim', 'Greater blue-eared starling', 'Lamprotornis chalybaeus');
insert into pet (name, animal, race) values ('Friedrick', 'Red-tailed wambenger', 'Phascogale calura');
insert into pet (name, animal, race) values ('Dru', 'Bear, grizzly', 'Ursus arctos');
insert into pet (name, animal, race) values ('Alfreda', 'Eastern white pelican', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Jodie', 'Otter, giant', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Rhona', 'Kudu, greater', 'Tragelaphus strepsiceros');
insert into pet (name, animal, race) values ('Gil', 'Yellow baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Livy', 'Vulture, griffon', 'Gyps fulvus');
insert into pet (name, animal, race) values ('Ibbie', 'White-bellied sea eagle', 'Haliaetus leucogaster');
insert into pet (name, animal, race) values ('Reilly', 'Dove, white-winged', 'Zenaida asiatica');
insert into pet (name, animal, race) values ('Corri', 'Indian jackal', 'Canis aureus');
insert into pet (name, animal, race) values ('Puff', 'Civet, small-toothed palm', 'Arctogalidia trivirgata');
insert into pet (name, animal, race) values ('Tommie', 'Red howler monkey', 'Alouatta seniculus');
insert into pet (name, animal, race) values ('Ardith', 'Kangaroo, jungle', 'Macropus agilis');
insert into pet (name, animal, race) values ('Jorey', 'Blue-tongued lizard', 'Tiliqua scincoides');
insert into pet (name, animal, race) values ('Arel', 'Owl, great horned', 'Bubo virginianus');
insert into pet (name, animal, race) values ('Marysa', 'Ostrich', 'Struthio camelus');
insert into pet (name, animal, race) values ('Brenden', 'Frogmouth, tawny', 'Podargus strigoides');
insert into pet (name, animal, race) values ('Filmore', 'Ring-tailed possum', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Valaria', 'Roller, lilac-breasted', 'Coracias caudata');
insert into pet (name, animal, race) values ('Herb', 'Common rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Skippy', 'Common waterbuck', 'Kobus defassa');
insert into pet (name, animal, race) values ('Peggie', 'Ox, musk', 'Ovibos moschatus');
insert into pet (name, animal, race) values ('Kerwinn', 'Antelope, four-horned', 'Tetracerus quadricornis');
insert into pet (name, animal, race) values ('Maryjo', 'Salmon, sockeye', 'Oncorhynchus nerka');
insert into pet (name, animal, race) values ('Sydney', 'American Virginia opossum', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Chan', 'Common zebra', 'Equus burchelli');
insert into pet (name, animal, race) values ('Tuckie', 'Hawk, galapagos', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Arlette', 'Yellow-bellied marmot', 'Marmota flaviventris');
insert into pet (name, animal, race) values ('Germaine', 'Baboon, gelada', 'Theropithecus gelada');
insert into pet (name, animal, race) values ('Kylen', 'Gonolek, burchell''s', 'Laniaurius atrococcineus');
insert into pet (name, animal, race) values ('Halsy', 'Magnificent frigate bird', 'Fregata magnificans');
insert into pet (name, animal, race) values ('Tiphanie', 'Leopard', 'Panthera pardus');
insert into pet (name, animal, race) values ('Mariska', 'Stick insect', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Dione', 'Asiatic jackal', 'Canis aureus');
insert into pet (name, animal, race) values ('Christye', 'White-tailed deer', 'Odocoilenaus virginianus');
insert into pet (name, animal, race) values ('Siana', 'Eastern white pelican', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Ewan', 'Australian magpie', 'Gymnorhina tibicen');
insert into pet (name, animal, race) values ('Tommi', 'Desert spiny lizard', 'Sceloporus magister');
insert into pet (name, animal, race) values ('Xerxes', 'Fox, bat-eared', 'Otocyon megalotis');
insert into pet (name, animal, race) values ('Olenolin', 'Pigeon, feral rock', 'Columba livia');
insert into pet (name, animal, race) values ('Alaric', 'Steller''s sea lion', 'Eumetopias jubatus');
insert into pet (name, animal, race) values ('Rickie', 'Hornbill, red-billed', 'Tockus erythrorhyncus');
insert into pet (name, animal, race) values ('Gregor', 'Goat, mountain', 'Oreamnos americanus');
insert into pet (name, animal, race) values ('Kassia', 'Black kite', 'Milvus migrans');
insert into pet (name, animal, race) values ('Alexina', 'Tsessebe', 'Damaliscus lunatus');
insert into pet (name, animal, race) values ('Rowen', 'Squirrel, eurasian red', 'Sciurus vulgaris');
insert into pet (name, animal, race) values ('Jermain', 'Pig-tailed macaque', 'Macaca nemestrina');
insert into pet (name, animal, race) values ('Phillida', 'Lemur, ring-tailed', 'Lemur catta');
insert into pet (name, animal, race) values ('Myrtle', 'Gray duiker', 'Sylvicapra grimma');
insert into pet (name, animal, race) values ('Russell', 'Quail, gambel''s', 'Callipepla gambelii');
insert into pet (name, animal, race) values ('Stevy', 'Red-billed tropic bird', 'Phaethon aethereus');
insert into pet (name, animal, race) values ('Cheri', 'Kinkajou', 'Potos flavus');
insert into pet (name, animal, race) values ('Hailey', 'Giant heron', 'Ardea golieth');
insert into pet (name, animal, race) values ('Joye', 'Wallaby, tammar', 'Macropus eugenii');
insert into pet (name, animal, race) values ('Vachel', 'Small-spotted genet', 'Genetta genetta');
insert into pet (name, animal, race) values ('Gweneth', 'Owl, australian masked', 'Tyto novaehollandiae');
insert into pet (name, animal, race) values ('Sella', 'Adouri (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Celina', 'Baleen whale', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Cinderella', 'Starling, greater blue-eared', 'Lamprotornis chalybaeus');
insert into pet (name, animal, race) values ('Margaretha', 'Gray heron', 'Ardea cinerea');
insert into pet (name, animal, race) values ('Ibby', 'Pelican, great white', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Whitman', 'Barbet, levaillant''s', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Cori', 'Wolf, mexican', 'Canis lupus baileyi');
insert into pet (name, animal, race) values ('Rhoda', 'Possum, ring-tailed', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Radcliffe', 'Lion, steller''s sea', 'Eumetopias jubatus');
insert into pet (name, animal, race) values ('Casper', 'Cat, civet', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Eva', 'Possum, western pygmy', 'Cercatetus concinnus');
insert into pet (name, animal, race) values ('Jonah', 'Cat, miner''s', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Heidi', 'African clawless otter', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Mirilla', 'Hawk, red-tailed', 'Buteo jamaicensis');
insert into pet (name, animal, race) values ('Brannon', 'Weaver, lesser masked', 'Ploceus intermedius');
insert into pet (name, animal, race) values ('Maynord', 'Dove, galapagos', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Stillmann', 'Slender-billed cockatoo', 'Cacatua tenuirostris');
insert into pet (name, animal, race) values ('Min', 'Butterfly, canadian tiger swallowtail', 'Papilio canadensis');
insert into pet (name, animal, race) values ('Engracia', 'Possum, ring-tailed', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Lonnie', 'Stilt, black-winged', 'Himantopus himantopus');
insert into pet (name, animal, race) values ('Charlean', 'African pied wagtail', 'Motacilla aguimp');
insert into pet (name, animal, race) values ('Patton', 'Dove, mourning collared', 'Streptopelia decipiens');
insert into pet (name, animal, race) values ('Joanna', 'Gambel''s quail', 'Callipepla gambelii');
insert into pet (name, animal, race) values ('Debee', 'Pelican, brown', 'Pelecanus occidentalis');
insert into pet (name, animal, race) values ('Jaime', 'Brazilian otter', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Clotilda', 'Four-spotted skimmer', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Aube', 'Eastern quoll', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Rupert', 'Blue crane', 'Anthropoides paradisea');
insert into pet (name, animal, race) values ('Thedrick', 'Southern tamandua', 'Tamandua tetradactyla');
insert into pet (name, animal, race) values ('Whitaker', 'Badger, eurasian', 'Meles meles');
insert into pet (name, animal, race) values ('Rona', 'Bustard, denham''s', 'Neotis denhami');
insert into pet (name, animal, race) values ('Storm', 'Turkey, common', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Elyn', 'Japanese macaque', 'Macaca fuscata');
insert into pet (name, animal, race) values ('Farica', 'Red-breasted cockatoo', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Farlee', 'Snake, eastern indigo', 'Drymarchon corias couperi');
insert into pet (name, animal, race) values ('Annnora', 'Fox, asian red', 'Vulpes vulpes');
insert into pet (name, animal, race) values ('Pansy', 'Rabbit, eastern cottontail', 'Sylvilagus floridanus');
insert into pet (name, animal, race) values ('Mab', 'Hornbill, leadbeateri''s ground', 'Bucorvus leadbeateri');
insert into pet (name, animal, race) values ('Florida', 'Leopard', 'Panthera pardus');
insert into pet (name, animal, race) values ('Nyssa', 'Cattle egret', 'Bubulcus ibis');
insert into pet (name, animal, race) values ('Virgina', 'Long-tailed jaeger', 'Stercorarius longicausus');
insert into pet (name, animal, race) values ('Lanae', 'Pelican, eastern white', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Alic', 'Asian foreset tortoise', 'Manouria emys');
insert into pet (name, animal, race) values ('Geneva', 'Pelican, australian', 'Pelecanus conspicillatus');
insert into pet (name, animal, race) values ('Axel', 'Rhea, gray', 'Rhea americana');
insert into pet (name, animal, race) values ('Robinia', 'Puna ibis', 'Plegadis ridgwayi');
insert into pet (name, animal, race) values ('Temp', 'Civet (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Lizabeth', 'Wolf spider', 'Lycosa godeffroyi');
insert into pet (name, animal, race) values ('Dina', 'Macaw, scarlet', 'Ara macao');
insert into pet (name, animal, race) values ('Josefa', 'Thrasher, curve-billed', 'Toxostoma curvirostre');
insert into pet (name, animal, race) values ('Sasha', 'Springhare', 'Pedetes capensis');
insert into pet (name, animal, race) values ('Gallard', 'Fox, north american red', 'Vulpes vulpes');
insert into pet (name, animal, race) values ('Munroe', 'Marine iguana', 'Amblyrhynchus cristatus');
insert into pet (name, animal, race) values ('Garv', 'Gull, swallow-tail', 'Creagrus furcatus');
insert into pet (name, animal, race) values ('Gare', 'Black-faced kangaroo', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Lonnard', 'Two-toed sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Inna', 'Loris, slender', 'Loris tardigratus');
insert into pet (name, animal, race) values ('Ronald', 'Pheasant, ring-necked', 'Phasianus colchicus');
insert into pet (name, animal, race) values ('Row', 'Black kite', 'Milvus migrans');
insert into pet (name, animal, race) values ('Dara', 'Eleven-banded armadillo (unidentified)', 'Cabassous sp.');
insert into pet (name, animal, race) values ('Milton', 'Cat, european wild', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Amery', 'Desert tortoise', 'Gopherus agassizii');
insert into pet (name, animal, race) values ('Aggy', 'Squirrel, red', 'Tamiasciurus hudsonicus');
insert into pet (name, animal, race) values ('Cindie', 'Robin, kalahari scrub', 'Certotrichas paena');
insert into pet (name, animal, race) values ('Zuzana', 'Boubou, southern', 'Laniarius ferrugineus');
insert into pet (name, animal, race) values ('Andrea', 'Lesser masked weaver', 'Ploceus intermedius');
insert into pet (name, animal, race) values ('Analiese', 'Waxbill, violet-eared', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Eb', 'Cuis', 'Microcavia australis');
insert into pet (name, animal, race) values ('Portie', 'Tortoise, burmese black mountain', 'Manouria emys');
insert into pet (name, animal, race) values ('Rikki', 'Heron, grey', 'Ardea cinerea');
insert into pet (name, animal, race) values ('Paolo', 'Kingfisher, white-throated', 'Halcyon smyrnesis');
insert into pet (name, animal, race) values ('Hilly', 'Gazer, sun', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Elmore', 'Impala', 'Aepyceros mylampus');
insert into pet (name, animal, race) values ('Blanche', 'Cat, ringtail', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Angeli', 'Glossy ibis', 'Plegadis falcinellus');
insert into pet (name, animal, race) values ('Clayton', 'Frog (unidentified)', 'Rana sp.');
insert into pet (name, animal, race) values ('Friedrich', 'American woodcock', 'Scolopax minor');
insert into pet (name, animal, race) values ('Helen-elizabeth', 'Mara', 'Dolichitus patagonum');
insert into pet (name, animal, race) values ('Athena', 'Burrowing owl', 'Speotyte cuniculata');
insert into pet (name, animal, race) values ('Onfroi', 'Water monitor', 'Varanus salvator');
insert into pet (name, animal, race) values ('Maren', 'Pampa gray fox', 'Pseudalopex gymnocercus');
insert into pet (name, animal, race) values ('Barny', 'Levaillant''s barbet', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Billy', 'Dragon, komodo', 'Varanus komodensis');
insert into pet (name, animal, race) values ('Cassandry', 'Indian leopard', 'Panthera pardus');
insert into pet (name, animal, race) values ('Celestyn', 'Savanna fox', 'Dusicyon thous');
insert into pet (name, animal, race) values ('Sharlene', 'Common shelduck', 'Tadorna tadorna');
insert into pet (name, animal, race) values ('Sid', 'Blue waxbill', 'Uraeginthus angolensis');
insert into pet (name, animal, race) values ('Dorine', 'Falcon, peregrine', 'Falco peregrinus');
insert into pet (name, animal, race) values ('Aldo', 'Monster, gila', 'Heloderma horridum');
insert into pet (name, animal, race) values ('Derby', 'Lemming, arctic', 'Dicrostonyx groenlandicus');
insert into pet (name, animal, race) values ('Sansone', 'Pied avocet', 'Recurvirostra avosetta');
insert into pet (name, animal, race) values ('Gary', 'Sparrow, rufous-collared', 'Zonotrichia capensis');
insert into pet (name, animal, race) values ('Virge', 'Chital', 'Axis axis');
insert into pet (name, animal, race) values ('Michaelina', 'White-eye, pale', 'Zosterops pallidus');
insert into pet (name, animal, race) values ('Laurens', 'Peregrine falcon', 'Falco peregrinus');
insert into pet (name, animal, race) values ('Rube', 'Carmine bee-eater', 'Merops nubicus');
insert into pet (name, animal, race) values ('Garrot', 'Turaco, violet-crested', 'Tauraco porphyrelophus');
insert into pet (name, animal, race) values ('Giacopo', 'White-eye, pale', 'Zosterops pallidus');
insert into pet (name, animal, race) values ('Cortney', 'Spoonbill, white', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Mariam', 'Australian brush turkey', 'Alectura lathami');
insert into pet (name, animal, race) values ('Afton', 'Bear, polar', 'Ursus maritimus');
insert into pet (name, animal, race) values ('Rodolphe', 'Anteater, australian spiny', 'Tachyglossus aculeatus');
insert into pet (name, animal, race) values ('Sybilla', 'Bunting, crested', 'Melophus lathami');
insert into pet (name, animal, race) values ('Gillian', 'Common melba finch', 'Pytilia melba');
insert into pet (name, animal, race) values ('Mohammed', 'Screamer, crested', 'Chauna torquata');
insert into pet (name, animal, race) values ('Georas', 'Kudu, greater', 'Tragelaphus strepsiceros');
insert into pet (name, animal, race) values ('Nicholas', 'Black-eyed bulbul', 'Pycnonotus barbatus');
insert into pet (name, animal, race) values ('Yalonda', 'Hoffman''s sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Flora', 'Hoary marmot', 'Marmota caligata');
insert into pet (name, animal, race) values ('Winny', 'Pied kingfisher', 'Ceryle rudis');
insert into pet (name, animal, race) values ('Coraline', 'Little brown bat', 'Myotis lucifugus');
insert into pet (name, animal, race) values ('Lesley', 'Wolf, common', 'Canis lupus');
insert into pet (name, animal, race) values ('Suzann', 'Secretary bird', 'Sagittarius serpentarius');
insert into pet (name, animal, race) values ('Sarah', 'Finch, common melba', 'Pytilia melba');
insert into pet (name, animal, race) values ('Leonerd', 'Turtle, long-necked', 'Chelodina longicollis');
insert into pet (name, animal, race) values ('Madelin', 'Anteater, australian spiny', 'Tachyglossus aculeatus');
insert into pet (name, animal, race) values ('Stillman', 'Dove, galapagos', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Billy', 'European spoonbill', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Petunia', 'Goldeneye, barrows', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Coletta', 'Partridge, coqui', 'Francolinus coqui');
insert into pet (name, animal, race) values ('Kleon', 'Gray rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Knox', 'Tortoise, galapagos', 'Geochelone elephantopus');
insert into pet (name, animal, race) values ('Davin', 'Kori bustard', 'Choriotis kori');
insert into pet (name, animal, race) values ('Stephen', 'White-rumped vulture', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('Daffi', 'Macaw, scarlet', 'Ara macao');
insert into pet (name, animal, race) values ('Nicoline', 'European stork', 'Ciconia ciconia');
insert into pet (name, animal, race) values ('Anders', 'Yellow-crowned night heron', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Zaria', 'Whale, southern right', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Drugi', 'Otter, cape clawless', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Jean', 'Albatross, waved', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Nikos', 'Yellow baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Debi', 'Grizzly bear', 'Ursus arctos');
insert into pet (name, animal, race) values ('Brocky', 'Tinamou, elegant crested', 'Eudromia elegans');
insert into pet (name, animal, race) values ('Francoise', 'Quoll, eastern', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Katleen', 'Boa, columbian rainbow', 'Epicrates cenchria maurus');
insert into pet (name, animal, race) values ('Kari', 'Dove, emerald-spotted wood', 'Turtur chalcospilos');
insert into pet (name, animal, race) values ('Paxton', 'Rainbow lory', 'Trichoglossus haematodus moluccanus');
insert into pet (name, animal, race) values ('Rowan', 'Kaffir cat', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Wilburt', 'Little blue penguin', 'Eudyptula minor');
insert into pet (name, animal, race) values ('Terencio', 'Black vulture', 'Aegypius tracheliotus');
insert into pet (name, animal, race) values ('Mic', 'Giant armadillo', 'Priodontes maximus');
insert into pet (name, animal, race) values ('Corilla', 'Puna ibis', 'Plegadis ridgwayi');
insert into pet (name, animal, race) values ('Tomi', 'Gull, pacific', 'Gabianus pacificus');
insert into pet (name, animal, race) values ('Berti', 'Ground legaan', 'Varanus sp.');
insert into pet (name, animal, race) values ('Arden', 'Pigeon, feral rock', 'Columba livia');
insert into pet (name, animal, race) values ('Axel', 'Shrike, southern white-crowned', 'Eurocephalus anguitimens');
insert into pet (name, animal, race) values ('Ailbert', 'Turkey vulture', 'Cathartes aura');
insert into pet (name, animal, race) values ('Clotilda', 'Elephant, asian', 'Elephas maximus bengalensis');
insert into pet (name, animal, race) values ('Travus', 'Whale, baleen', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Joycelin', 'Goose, cape barren', 'Cereopsis novaehollandiae');
insert into pet (name, animal, race) values ('Nataniel', 'White-throated toucan', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Thedric', 'Stork, openbill', 'Anastomus oscitans');
insert into pet (name, animal, race) values ('Joelynn', 'Caracara (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Elberta', 'Fat-tailed dunnart', 'Smithopsis crassicaudata');
insert into pet (name, animal, race) values ('Dar', 'Lapwing (unidentified)', 'Vanellus sp.');
insert into pet (name, animal, race) values ('Kimbell', 'Galah', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Sinclair', 'Boa, columbian rainbow', 'Epicrates cenchria maurus');
insert into pet (name, animal, race) values ('Vanya', 'Yellow mongoose', 'Cynictis penicillata');
insert into pet (name, animal, race) values ('Beitris', 'Smith''s bush squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Helen-elizabeth', 'African red-eyed bulbul', 'Pycnonotus nigricans');
insert into pet (name, animal, race) values ('Hedda', 'Springbok', 'Antidorcas marsupialis');
insert into pet (name, animal, race) values ('Nickie', 'Small-clawed otter', 'Aonyx cinerea');
insert into pet (name, animal, race) values ('Franni', 'Deer, swamp', 'Cervus duvauceli');
insert into pet (name, animal, race) values ('Elisabeth', 'Kookaburra, laughing', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Ynez', 'Crab-eating fox', 'Dusicyon thous');
insert into pet (name, animal, race) values ('Annabelle', 'Duck, comb', 'Sarkidornis melanotos');
insert into pet (name, animal, race) values ('Kelci', 'Lion, african', 'Panthera leo');
insert into pet (name, animal, race) values ('Licha', 'Eagle, white-bellied sea', 'Haliaetus leucogaster');
insert into pet (name, animal, race) values ('Kristina', 'Goose, spur-winged', 'Plectopterus gambensis');
insert into pet (name, animal, race) values ('Jermaine', 'Otter, cape clawless', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Ruttger', 'Bohor reedbuck', 'Redunca redunca');
insert into pet (name, animal, race) values ('Rosanna', 'Dragon, komodo', 'Varanus komodensis');
insert into pet (name, animal, race) values ('Malinde', 'Collared lizard', 'Crotaphytus collaris');
insert into pet (name, animal, race) values ('Blakelee', 'Jungle cat', 'Felis chaus');
insert into pet (name, animal, race) values ('Kingsly', 'Capuchin, black-capped', 'Cebus apella');
insert into pet (name, animal, race) values ('Lorenza', 'Huron', 'Galictis vittata');
insert into pet (name, animal, race) values ('Brigid', 'Caracal', 'Felis caracal');
insert into pet (name, animal, race) values ('Corby', 'Bee-eater, white-fronted', 'Merops bullockoides');
insert into pet (name, animal, race) values ('Manuel', 'Lion, mountain', 'Felis concolor');
insert into pet (name, animal, race) values ('Oralee', 'White-bellied sea eagle', 'Haliaetus leucogaster');
insert into pet (name, animal, race) values ('Kelwin', 'Blue-tongued lizard', 'Tiliqua scincoides');
insert into pet (name, animal, race) values ('Evelin', 'Mockingbird, galapagos', 'Nesomimus trifasciatus');
insert into pet (name, animal, race) values ('Kristofor', 'Cat, ringtail', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Veronique', 'Pintail, white-cheeked', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Cob', 'Gerbil (unidentified)', 'Gerbillus sp.');
insert into pet (name, animal, race) values ('Kirsti', 'Genet, small-spotted', 'Genetta genetta');
insert into pet (name, animal, race) values ('Marisa', 'Vulture, griffon', 'Gyps fulvus');
insert into pet (name, animal, race) values ('Ainslie', 'Bulbul, african red-eyed', 'Pycnonotus nigricans');
insert into pet (name, animal, race) values ('Anna-maria', 'Mallard', 'Anas platyrhynchos');
insert into pet (name, animal, race) values ('Sauncho', 'Eagle, crowned', 'Spizaetus coronatus');
insert into pet (name, animal, race) values ('Chloette', 'Kori bustard', 'Choriotis kori');
insert into pet (name, animal, race) values ('Elfie', 'Civet, common palm', 'Paradoxurus hermaphroditus');
insert into pet (name, animal, race) values ('Dulciana', 'Australian pelican', 'Pelecanus conspicillatus');
insert into pet (name, animal, race) values ('Fern', 'Black-necked stork', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Saundra', 'Squirrel, richardson''s ground', 'Spermophilus richardsonii');
insert into pet (name, animal, race) values ('Zonda', 'Fisher', 'Martes pennanti');
insert into pet (name, animal, race) values ('Ruperta', 'Mountain duck', 'Hymenolaimus malacorhynchus');
insert into pet (name, animal, race) values ('Hermann', 'Ring dove', 'Columba palumbus');
insert into pet (name, animal, race) values ('Rita', 'Genet, common', 'Genetta genetta');
insert into pet (name, animal, race) values ('Pattie', 'Common goldeneye', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Hakeem', 'Dama wallaby', 'Macropus eugenii');
insert into pet (name, animal, race) values ('Wadsworth', 'Sandhill crane', 'Grus canadensis');
insert into pet (name, animal, race) values ('Patricia', 'Marshbird, brown and yellow', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Claudelle', 'American Virginia opossum', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Ilyssa', 'Fairy penguin', 'Eudyptula minor');
insert into pet (name, animal, race) values ('Tally', 'Peccary, collared', 'Tayassu tajacu');
insert into pet (name, animal, race) values ('Cally', 'Squirrel, antelope ground', 'Ammospermophilus nelsoni');
insert into pet (name, animal, race) values ('Maureen', 'American black bear', 'Ursus americanus');
insert into pet (name, animal, race) values ('Susannah', 'Quoll, eastern', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Karlene', 'Bandicoot, short-nosed', 'Isoodon obesulus');
insert into pet (name, animal, race) values ('Osborn', 'African clawless otter', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Phip', 'Gorilla, western lowland', 'Gorilla gorilla');
insert into pet (name, animal, race) values ('Reginald', 'Insect, stick', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Collette', 'Red-breasted nuthatch', 'Sitta canadensis');
insert into pet (name, animal, race) values ('Malinda', 'Malagasy ground boa', 'Acrantophis madagascariensis');
insert into pet (name, animal, race) values ('Brion', 'American beaver', 'Castor canadensis');
insert into pet (name, animal, race) values ('Faith', 'Grizzly bear', 'Ursus arctos');
insert into pet (name, animal, race) values ('Shayne', 'Campo flicker', 'Colaptes campestroides');
insert into pet (name, animal, race) values ('Nananne', 'Kangaroo, western grey', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Walliw', 'Beaver, american', 'Castor canadensis');
insert into pet (name, animal, race) values ('Frederik', 'Eurasian beaver', 'Castor fiber');
insert into pet (name, animal, race) values ('Lilyan', 'Possum, golden brush-tailed', 'Trichosurus vulpecula');
insert into pet (name, animal, race) values ('Kimberlee', 'Blesbok', 'Damaliscus dorcas');
insert into pet (name, animal, race) values ('Addy', 'Stork, saddle-billed', 'Ephipplorhynchus senegalensis');
insert into pet (name, animal, race) values ('Onofredo', 'African wild cat', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Harli', 'Salmon, sockeye', 'Oncorhynchus nerka');
insert into pet (name, animal, race) values ('Marwin', 'Macaw, green-winged', 'Ara chloroptera');
insert into pet (name, animal, race) values ('Jesse', 'Royal tern', 'Thalasseus maximus');
insert into pet (name, animal, race) values ('Lindsay', 'Burmese brown mountain tortoise', 'Manouria emys');
insert into pet (name, animal, race) values ('Garrett', 'Goose, andean', 'Chloephaga melanoptera');
insert into pet (name, animal, race) values ('Breena', 'Oryx, beisa', 'Oryx gazella');
insert into pet (name, animal, race) values ('Josefina', 'Antelope ground squirrel', 'Ammospermophilus nelsoni');
insert into pet (name, animal, race) values ('Athena', 'Brown brocket', 'Mazama gouazoubira');
insert into pet (name, animal, race) values ('Constance', 'Cockatoo, slender-billed', 'Cacatua tenuirostris');
insert into pet (name, animal, race) values ('Alvinia', 'Scottish highland cow', 'Bos taurus');
insert into pet (name, animal, race) values ('Bethena', 'Richardson''s ground squirrel', 'Spermophilus richardsonii');
insert into pet (name, animal, race) values ('Munmro', 'Arctic hare', 'Lepus arcticus');
insert into pet (name, animal, race) values ('Audrie', 'Porcupine, north american', 'Erethizon dorsatum');
insert into pet (name, animal, race) values ('Karil', 'Ring-tailed lemur', 'Lemur catta');
insert into pet (name, animal, race) values ('Zea', 'Nyala', 'Tragelaphus angasi');
insert into pet (name, animal, race) values ('Ronny', 'Tarantula', 'Lasiodora parahybana');
insert into pet (name, animal, race) values ('Sampson', 'Gull, dusky', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Ram', 'Prairie falcon', 'Falco mexicanus');
insert into pet (name, animal, race) values ('Hilario', 'Puffin, horned', 'Fratercula corniculata');
insert into pet (name, animal, race) values ('Arlin', 'Armadillo, common long-nosed', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Marquita', 'African lion', 'Panthera leo');
insert into pet (name, animal, race) values ('Siana', 'Hoffman''s sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Alanson', 'Mongoose, javan gold-spotted', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Lacie', 'Tern, white-winged black', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Carlin', 'Little cormorant', 'Phalacrocorax niger');
insert into pet (name, animal, race) values ('Mathe', 'Stork, black-necked', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Thekla', 'Greater rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Linc', 'Polecat, african', 'Ictonyx striatus');
insert into pet (name, animal, race) values ('Morly', 'White rhinoceros', 'Ceratotherium simum');
insert into pet (name, animal, race) values ('Gregor', 'Snowy sheathbill', 'Chionis alba');
insert into pet (name, animal, race) values ('Angelita', 'Turkey, wild', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Wilona', 'Bobcat', 'Felis rufus');
insert into pet (name, animal, race) values ('Gallagher', 'Kangaroo, black-faced', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Gorden', 'Common wallaroo', 'Macropus robustus');
insert into pet (name, animal, race) values ('Bartlett', 'Gull, silver', 'Larus novaehollandiae');
insert into pet (name, animal, race) values ('Elna', 'Arctic lemming', 'Dicrostonyx groenlandicus');
insert into pet (name, animal, race) values ('Rusty', 'Armadillo, nine-banded', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Meier', 'Springbuck', 'Antidorcas marsupialis');
insert into pet (name, animal, race) values ('Hetti', 'Kite, black', 'Milvus migrans');
insert into pet (name, animal, race) values ('Marta', 'American Virginia opossum', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Nada', 'Raven, white-necked', 'Corvus albicollis');
insert into pet (name, animal, race) values ('Janela', 'Laughing dove', 'Streptopelia senegalensis');
insert into pet (name, animal, race) values ('Melisent', 'Agama lizard (unidentified)', 'Agama sp.');
insert into pet (name, animal, race) values ('Cesar', 'Pied crow', 'Corvus albus');
insert into pet (name, animal, race) values ('Pebrook', 'Heron, green', 'Butorides striatus');
insert into pet (name, animal, race) values ('Ebenezer', 'Trumpeter swan', 'Cygnus buccinator');
insert into pet (name, animal, race) values ('Grete', 'Plains zebra', 'Equus burchelli');
insert into pet (name, animal, race) values ('Marya', 'Eurasian badger', 'Meles meles');
insert into pet (name, animal, race) values ('Emmit', 'Springbok', 'Antidorcas marsupialis');
insert into pet (name, animal, race) values ('Lindsey', 'Bahama pintail', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Bernie', 'Weaver, sociable', 'Philetairus socius');
insert into pet (name, animal, race) values ('Catriona', 'Yellow-billed stork', 'Mycteria ibis');
insert into pet (name, animal, race) values ('Sammie', 'Gazer, sun', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Carolyne', 'Eagle, african fish', 'Haliaetus vocifer');
insert into pet (name, animal, race) values ('Alexandro', 'Javan gold-spotted mongoose', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Bail', 'Snake, western patch-nosed', 'Salvadora hexalepis');
insert into pet (name, animal, race) values ('Natty', 'Ibis, sacred', 'Threskionis aethiopicus');
insert into pet (name, animal, race) values ('Willa', 'Viper, egyptian', 'Naja haje');
insert into pet (name, animal, race) values ('Minerva', 'House sparrow', 'Passer domesticus');
insert into pet (name, animal, race) values ('Hester', 'Dove, little brown', 'Streptopelia senegalensis');
insert into pet (name, animal, race) values ('Madelena', 'Blue-tongued skink', 'Tiliqua scincoides');
insert into pet (name, animal, race) values ('Kat', 'Bat, little brown', 'Myotis lucifugus');
insert into pet (name, animal, race) values ('Jammal', 'Sugar glider', 'Petaurus breviceps');
insert into pet (name, animal, race) values ('Wittie', 'Cardinal, red-capped', 'Paroaria gularis');
insert into pet (name, animal, race) values ('Gertruda', 'Macaque, rhesus', 'Macaca mulatta');
insert into pet (name, animal, race) values ('Nikki', 'Buttermilk snake', 'Coluber constrictor');
insert into pet (name, animal, race) values ('Jehanna', 'Gull, pacific', 'Gabianus pacificus');
insert into pet (name, animal, race) values ('Dukie', 'Gull, dusky', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Audie', 'American bison', 'Bison bison');
insert into pet (name, animal, race) values ('Madeleine', 'Eastern grey kangaroo', 'Macropus giganteus');
insert into pet (name, animal, race) values ('Inna', 'Knob-nosed goose', 'Sarkidornis melanotos');
insert into pet (name, animal, race) values ('Darelle', 'Chipmunk, least', 'Eutamias minimus');
insert into pet (name, animal, race) values ('Nicola', 'Crake, african black', 'Limnocorax flavirostra');
insert into pet (name, animal, race) values ('Aharon', 'Giant armadillo', 'Priodontes maximus');
insert into pet (name, animal, race) values ('Jaquith', 'Common turkey', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Ariana', 'Whale, killer', 'Orcinus orca');
insert into pet (name, animal, race) values ('Garfield', 'Kangaroo, eastern grey', 'Macropus giganteus');
insert into pet (name, animal, race) values ('Marcelo', 'Beaver, north american', 'Castor canadensis');
insert into pet (name, animal, race) values ('Greg', 'Serval', 'Felis serval');
insert into pet (name, animal, race) values ('Nev', 'Phalarope, red', 'Phalaropus fulicarius');
insert into pet (name, animal, race) values ('Frayda', 'Rhesus macaque', 'Macaca mulatta');
insert into pet (name, animal, race) values ('Derron', 'Monitor, water', 'Varanus salvator');
insert into pet (name, animal, race) values ('Aubrey', 'Killer whale', 'Orcinus orca');
insert into pet (name, animal, race) values ('Joel', 'White-faced whistling duck', 'Dendrocygna viduata');
insert into pet (name, animal, race) values ('Christine', 'White stork', 'Ciconia ciconia');
insert into pet (name, animal, race) values ('Kariotta', 'Quoll, eastern', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Evered', 'Steller''s sea lion', 'Eumetopias jubatus');
insert into pet (name, animal, race) values ('Wesley', 'Heron, yellow-crowned night', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Alie', 'Moose', 'Alces alces');
insert into pet (name, animal, race) values ('Merrill', 'Glider, sugar', 'Petaurus breviceps');
insert into pet (name, animal, race) values ('Michaella', 'Squirrel, antelope ground', 'Ammospermophilus nelsoni');
insert into pet (name, animal, race) values ('Nerti', 'Columbian rainbow boa', 'Epicrates cenchria maurus');
insert into pet (name, animal, race) values ('Zita', 'Raccoon, crab-eating', 'Procyon cancrivorus');
insert into pet (name, animal, race) values ('Em', 'Feral rock pigeon', 'Columba livia');
insert into pet (name, animal, race) values ('Serena', 'Owl, madagascar hawk', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Clint', 'Common pheasant', 'Phasianus colchicus');
insert into pet (name, animal, race) values ('Brockie', 'Black rhinoceros', 'Diceros bicornis');
insert into pet (name, animal, race) values ('Hewet', 'Small Indian mongoose', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Fanya', 'Slender loris', 'Loris tardigratus');
insert into pet (name, animal, race) values ('Fabien', 'Lemming, arctic', 'Dicrostonyx groenlandicus');
insert into pet (name, animal, race) values ('Gamaliel', 'Squirrel, grey-footed', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Wilfrid', 'Cook''s tree boa', 'Corallus hortulanus cooki');
insert into pet (name, animal, race) values ('Brier', 'Oystercatcher, blackish', 'Haematopus ater');
insert into pet (name, animal, race) values ('Bradan', 'Hottentot teal', 'Anas punctata');
insert into pet (name, animal, race) values ('Germayne', 'Chameleon (unidentified)', 'Chamaelo sp.');
insert into pet (name, animal, race) values ('Barbara', 'Phascogale, brush-tailed', 'Phascogale tapoatafa');
insert into pet (name, animal, race) values ('Worthington', 'Opossum, american virginia', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Sonja', 'White-lipped peccary', 'Tayassu pecari');
insert into pet (name, animal, race) values ('Celia', 'Mule deer', 'Odocoileus hemionus');
insert into pet (name, animal, race) values ('Callie', 'African lynx', 'Felis caracal');
insert into pet (name, animal, race) values ('Fernande', 'Capuchin, weeper', 'Cebus nigrivittatus');
