insert into pet (name, animal, race) values ('Lucrèce', 'Cobra, egyptian', 'Naja haje');
insert into pet (name, animal, race) values ('Faîtes', 'Llama', 'Lama glama');
insert into pet (name, animal, race) values ('Marie-noël', 'Whale, baleen', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Célestine', 'Yellow-bellied marmot', 'Marmota flaviventris');
insert into pet (name, animal, race) values ('Sòng', 'Bulbul, black-eyed', 'Pycnonotus barbatus');
insert into pet (name, animal, race) values ('Maëlys', 'Greater rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Vénus', 'Otter, african clawless', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Nélie', 'Warthog', 'Phacochoerus aethiopus');
insert into pet (name, animal, race) values ('Anaël', 'Wolf spider', 'Lycosa godeffroyi');
insert into pet (name, animal, race) values ('Göran', 'Bottle-nose dolphin', 'Tursiops truncatus');
insert into pet (name, animal, race) values ('Åke', 'Red-winged blackbird', 'Agelaius phoeniceus');
insert into pet (name, animal, race) values ('Bécassine', 'Eastern indigo snake', 'Drymarchon corias couperi');
insert into pet (name, animal, race) values ('Kù', 'Ring-tailed possum', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Mylène', 'Waved albatross', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Pål', 'Dingo', 'Canis dingo');
insert into pet (name, animal, race) values ('Åslög', 'Prehensile-tailed porcupine', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Maïly', 'Rattlesnake, horned', 'Crotalus cerastes');
insert into pet (name, animal, race) values ('Célestine', 'Weaver, chestnut', 'Ploceus rubiginosus');
insert into pet (name, animal, race) values ('Naéva', 'Wallaby, red-necked', 'Macropus rufogriseus');
insert into pet (name, animal, race) values ('Dà', 'Owl, white-browed', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Dafnée', 'Blue fox', 'Alopex lagopus');
insert into pet (name, animal, race) values ('Dà', 'Tammar wallaby', 'Macropus eugenii');
insert into pet (name, animal, race) values ('Mélodie', 'Phalarope, red', 'Phalaropus fulicarius');
insert into pet (name, animal, race) values ('Örjan', 'Tortoise, burmese black mountain', 'Manouria emys');
insert into pet (name, animal, race) values ('Adélie', 'Heron, black-crowned night', 'Nycticorax nycticorax');
insert into pet (name, animal, race) values ('Gaïa', 'Gemsbok', 'Oryx gazella');
insert into pet (name, animal, race) values ('Gösta', 'Blackbird, red-winged', 'Agelaius phoeniceus');
insert into pet (name, animal, race) values ('Lauréna', 'Zorro, azara''s', 'Pseudalopex gymnocercus');
insert into pet (name, animal, race) values ('Magdalène', 'Yellow-brown sungazer', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Naëlle', 'Sandgrouse, yellow-throated', 'Pterocles gutturalis');
insert into pet (name, animal, race) values ('Lorène', 'Richardson''s ground squirrel', 'Spermophilus richardsonii');
insert into pet (name, animal, race) values ('Bénédicte', 'Golden eagle', 'Aquila chrysaetos');
insert into pet (name, animal, race) values ('Clélia', 'Indian star tortoise', 'Geochelone elegans');
insert into pet (name, animal, race) values ('Alizée', 'Cockatoo, long-billed', 'Cacatua tenuirostris');
insert into pet (name, animal, race) values ('Méline', 'Porcupine, tree', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Liè', 'Brindled gnu', 'Connochaetus taurinus');
insert into pet (name, animal, race) values ('Miléna', 'Heron, giant', 'Ardea golieth');
insert into pet (name, animal, race) values ('Adélaïde', 'White-necked stork', 'Ciconia episcopus');
insert into pet (name, animal, race) values ('Célia', 'Goose, knob-nosed', 'Sarkidornis melanotos');
insert into pet (name, animal, race) values ('Yè', 'Pied cormorant', 'Phalacrocorax varius');
insert into pet (name, animal, race) values ('Kévina', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Örjan', 'Mongoose, small indian', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Stéphanie', 'Ibis, glossy', 'Plegadis falcinellus');
insert into pet (name, animal, race) values ('Ophélie', 'Lion, california sea', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Lèi', 'Impala', 'Aepyceros mylampus');
insert into pet (name, animal, race) values ('Simplifiés', 'Macaw, green-winged', 'Ara chloroptera');
insert into pet (name, animal, race) values ('Renée', 'Kelp gull', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Kù', 'Avocet, pied', 'Recurvirostra avosetta');
insert into pet (name, animal, race) values ('Réservés', 'Genoveva', 'Junonia genoveua');
insert into pet (name, animal, race) values ('Léandre', 'Pelican, eastern white', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Kuí', 'Mongoose, yellow', 'Cynictis penicillata');
insert into pet (name, animal, race) values ('Esbjörn', 'Eagle, crowned', 'Spizaetus coronatus');
insert into pet (name, animal, race) values ('Zhì', 'Tiger snake', 'Notechis semmiannulatus');
insert into pet (name, animal, race) values ('Tú', 'Red-headed woodpecker', 'Melanerpes erythrocephalus');
insert into pet (name, animal, race) values ('Vérane', 'Nutcracker, clark''s', 'Nucifraga columbiana');
insert into pet (name, animal, race) values ('Cécilia', 'Baboon, savanna', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Tú', 'Possum, ring-tailed', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Ruò', 'Southern brown bandicoot', 'Isoodon obesulus');
insert into pet (name, animal, race) values ('Illustrée', 'Macaque, japanese', 'Macaca fuscata');
insert into pet (name, animal, race) values ('Daphnée', 'Coqui francolin', 'Francolinus coqui');
insert into pet (name, animal, race) values ('Loïca', 'Raven, cape', 'Corvus albicollis');
insert into pet (name, animal, race) values ('Félicie', 'Cat, kaffir', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Mélys', 'Shrike, common boubou', 'Laniarius ferrugineus');
insert into pet (name, animal, race) values ('Thérèse', 'Kelp gull', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Mårten', 'Stork, woolly-necked', 'Ciconia episcopus');
insert into pet (name, animal, race) values ('André', 'Blue crane', 'Anthropoides paradisea');
insert into pet (name, animal, race) values ('Märta', 'Waxbill, violet-eared', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Maïlis', 'Feathertail glider', 'Acrobates pygmaeus');
insert into pet (name, animal, race) values ('Cécile', 'Brindled gnu', 'Connochaetus taurinus');
insert into pet (name, animal, race) values ('Aimée', 'Thirteen-lined squirrel', 'Spermophilus tridecemlineatus');
insert into pet (name, animal, race) values ('Noëlla', 'Wolf, mexican', 'Canis lupus baileyi');
insert into pet (name, animal, race) values ('Lucrèce', 'Heron, black-crowned night', 'Nycticorax nycticorax');
insert into pet (name, animal, race) values ('Maëly', 'Plover, blacksmith', 'Vanellus armatus');
insert into pet (name, animal, race) values ('Tú', 'Blue peacock', 'Pavo cristatus');
insert into pet (name, animal, race) values ('Maéna', 'Spotted wood sandpiper', 'Tringa glareola');
insert into pet (name, animal, race) values ('Régine', 'Moccasin, water', 'Agkistrodon piscivorus');
insert into pet (name, animal, race) values ('Faîtes', 'Harbor seal', 'Phoca vitulina');
insert into pet (name, animal, race) values ('Chloé', 'Lion, asian', 'Panthera leo persica');
insert into pet (name, animal, race) values ('Faîtes', 'Capuchin, black-capped', 'Cebus apella');
insert into pet (name, animal, race) values ('Adélaïde', 'Kafue flats lechwe', 'Kobus leche robertsi');
insert into pet (name, animal, race) values ('Océane', 'White-faced whistling duck', 'Dendrocygna viduata');
insert into pet (name, animal, race) values ('Dù', 'Woodrat (unidentified)', 'Neotoma sp.');
insert into pet (name, animal, race) values ('Erwéi', 'Goose, egyptian', 'Alopochen aegyptiacus');
insert into pet (name, animal, race) values ('Frédérique', 'Desert tortoise', 'Gopherus agassizii');
insert into pet (name, animal, race) values ('Célestine', 'White-fronted bee-eater', 'Merops bullockoides');
insert into pet (name, animal, race) values ('Ráo', 'Seal, harbor', 'Phoca vitulina');
insert into pet (name, animal, race) values ('Ruò', 'Francolin, swainson''s', 'Francolinus swainsonii');
insert into pet (name, animal, race) values ('Rachèle', 'Grenadier, purple', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Loïca', 'Brown capuchin', 'Cebus apella');
insert into pet (name, animal, race) values ('Aimée', 'Swainson''s francolin', 'Francolinus swainsonii');
insert into pet (name, animal, race) values ('Crééz', 'Bottle-nose dolphin', 'Tursiops truncatus');
insert into pet (name, animal, race) values ('Dafnée', 'White-throated toucan', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Aloïs', 'Lesser mouse lemur', 'Microcebus murinus');
insert into pet (name, animal, race) values ('Lyséa', 'Peregrine falcon', 'Falco peregrinus');
insert into pet (name, animal, race) values ('Maïlis', 'Possum, ring-tailed', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Stévina', 'Golden jackal', 'Canis aureus');
insert into pet (name, animal, race) values ('Erwéi', 'Sheathbill, snowy', 'Chionis alba');
insert into pet (name, animal, race) values ('Méghane', 'Glossy ibis', 'Plegadis falcinellus');
insert into pet (name, animal, race) values ('Måns', 'Great egret', 'Casmerodius albus');
insert into pet (name, animal, race) values ('Anaëlle', 'Waved albatross', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Estée', 'Hyrax', 'Dendrohyrax brucel');
insert into pet (name, animal, race) values ('Gaïa', 'Chital', 'Axis axis');
insert into pet (name, animal, race) values ('Lyséa', 'Galapagos tortoise', 'Geochelone elephantopus');
insert into pet (name, animal, race) values ('Irène', 'Brolga crane', 'Grus rubicundus');
insert into pet (name, animal, race) values ('Dafnée', 'Heron, black-crowned night', 'Nycticorax nycticorax');
insert into pet (name, animal, race) values ('Publicité', 'Reindeer', 'Rangifer tarandus');
insert into pet (name, animal, race) values ('Naéva', 'Great egret', 'Casmerodius albus');
insert into pet (name, animal, race) values ('Björn', 'Purple moorhen', 'Porphyrio porphyrio');
insert into pet (name, animal, race) values ('Chloé', 'Crown of thorns starfish', 'Acanthaster planci');
insert into pet (name, animal, race) values ('Aloïs', 'Mexican boa', 'Boa constrictor mexicana');
insert into pet (name, animal, race) values ('Eléa', 'Brocket, brown', 'Mazama gouazoubira');
insert into pet (name, animal, race) values ('Lóng', 'Snow goose', 'Anser caerulescens');
insert into pet (name, animal, race) values ('Göran', 'Yellow-necked spurfowl', 'Francolinus leucoscepus');
insert into pet (name, animal, race) values ('Liè', 'Ringtail cat', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Fèi', 'Goose, snow', 'Anser caerulescens');
insert into pet (name, animal, race) values ('Annotée', 'Greater rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Bérengère', 'European wild cat', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Océane', 'Jackrabbit, white-tailed', 'Lepus townsendii');
insert into pet (name, animal, race) values ('Judicaël', 'White-rumped vulture', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('Mahélie', 'Squirrel, uinta ground', 'Spermophilus armatus');
insert into pet (name, animal, race) values ('Bénédicte', 'Bare-faced go away bird', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Mélina', 'Grison', 'Galictis vittata');
insert into pet (name, animal, race) values ('Laurélie', 'Sage grouse', 'Centrocercus urophasianus');
insert into pet (name, animal, race) values ('Pélagie', 'Four-striped grass mouse', 'Rhabdomys pumilio');
insert into pet (name, animal, race) values ('Marylène', 'Bear, polar', 'Ursus maritimus');
insert into pet (name, animal, race) values ('Clémentine', 'Squirrel, eurasian red', 'Sciurus vulgaris');
insert into pet (name, animal, race) values ('Méghane', 'Crane, blue', 'Anthropoides paradisea');
insert into pet (name, animal, race) values ('Tú', 'Squirrel, pine', 'Tamiasciurus hudsonicus');
insert into pet (name, animal, race) values ('Håkan', 'Feral rock pigeon', 'Columba livia');
insert into pet (name, animal, race) values ('Laïla', 'Pronghorn', 'Antilocapra americana');
insert into pet (name, animal, race) values ('Bécassine', 'Toucan, white-throated', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Maëlla', 'Laughing kookaburra', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Pélagie', 'Madagascar fruit bat', 'Pteropus rufus');
insert into pet (name, animal, race) values ('Esbjörn', 'Turkey, wild', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Maéna', 'Prehensile-tailed porcupine', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Lài', 'Egret, cattle', 'Bubulcus ibis');
insert into pet (name, animal, race) values ('Maëlyss', 'Gray langur', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Mahélie', 'African skink', 'Mabuya spilogaster');
insert into pet (name, animal, race) values ('Nélie', 'Cormorant, king', 'Phalacrocorax albiventer');
insert into pet (name, animal, race) values ('Styrbjörn', 'Yellow-crowned night heron', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Zoé', 'Spur-winged goose', 'Plectopterus gambensis');
insert into pet (name, animal, race) values ('Léana', 'Roadrunner, greater', 'Geococcyx californianus');
insert into pet (name, animal, race) values ('Marie-hélène', 'Argalis', 'Ovis ammon');
insert into pet (name, animal, race) values ('Tú', 'African fish eagle', 'Haliaetus vocifer');
insert into pet (name, animal, race) values ('Angélique', 'White-fronted bee-eater', 'Merops bullockoides');
insert into pet (name, animal, race) values ('Mélina', 'Komodo dragon', 'Varanus komodensis');
insert into pet (name, animal, race) values ('Tú', 'Porcupine, north american', 'Erethizon dorsatum');
insert into pet (name, animal, race) values ('Noémie', 'Blue-tongued lizard', 'Tiliqua scincoides');
insert into pet (name, animal, race) values ('Hélèna', 'Goose, canada', 'Branta canadensis');
insert into pet (name, animal, race) values ('Dafnée', 'White rhinoceros', 'Ceratotherium simum');
insert into pet (name, animal, race) values ('Géraldine', 'Phalarope, northern', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Maïwenn', 'Western patch-nosed snake', 'Salvadora hexalepis');
insert into pet (name, animal, race) values ('Publicité', 'Macaque, japanese', 'Macaca fuscata');
insert into pet (name, animal, race) values ('Anaé', 'Violet-eared waxbill', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Océanne', 'Bottle-nose dolphin', 'Tursiops truncatus');
insert into pet (name, animal, race) values ('Maëly', 'Coot, red-knobbed', 'Fulica cristata');
insert into pet (name, animal, race) values ('Clélia', 'Southern brown bandicoot', 'Isoodon obesulus');
insert into pet (name, animal, race) values ('Maëlla', 'Striated heron', 'Butorides striatus');
insert into pet (name, animal, race) values ('Sélène', 'Badger, european', 'Meles meles');
insert into pet (name, animal, race) values ('Lén', 'Bird, bare-faced go away', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Léone', 'Gulls (unidentified)', 'Larus sp.');
insert into pet (name, animal, race) values ('Loïs', 'Opossum, american virginia', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Laïla', 'White-eye, cape', 'Zosterops pallidus');
insert into pet (name, animal, race) values ('Gérald', 'Hawk-eagle, crowned', 'Spizaetus coronatus');
insert into pet (name, animal, race) values ('Bérangère', 'Colobus, magistrate black', 'Colobus guerza');
insert into pet (name, animal, race) values ('Lóng', 'Lemming, collared', 'Dicrostonyx groenlandicus');
insert into pet (name, animal, race) values ('Audréanne', 'Brown and yellow marshbird', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Estève', 'Asian false vampire bat', 'Megaderma spasma');
insert into pet (name, animal, race) values ('Jú', 'Dog, raccoon', 'Nyctereutes procyonoides');
insert into pet (name, animal, race) values ('Eléonore', 'Owl, burrowing', 'Speotyte cuniculata');
insert into pet (name, animal, race) values ('Méghane', 'Antelope ground squirrel', 'Ammospermophilus nelsoni');
insert into pet (name, animal, race) values ('Geneviève', 'Kirk''s dik dik', 'Madoqua kirkii');
insert into pet (name, animal, race) values ('Rébecca', 'Owl, madagascar hawk', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Loïca', 'Tawny frogmouth', 'Podargus strigoides');
insert into pet (name, animal, race) values ('Dafnée', 'Brown pelican', 'Pelecanus occidentalis');
insert into pet (name, animal, race) values ('Naëlle', 'Squirrel, thirteen-lined', 'Spermophilus tridecemlineatus');
insert into pet (name, animal, race) values ('Cunégonde', 'Toucan, white-throated', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Célestine', 'Gull, swallow-tail', 'Creagrus furcatus');
insert into pet (name, animal, race) values ('Cécilia', 'Nile crocodile', 'Crocodylus niloticus');
insert into pet (name, animal, race) values ('Noémie', 'Wambenger, red-tailed', 'Phascogale calura');
insert into pet (name, animal, race) values ('Göran', 'Red lava crab', 'Graspus graspus');
insert into pet (name, animal, race) values ('Séverine', 'Whale, baleen', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Cunégonde', 'Goose, cereopsis', 'Cereopsis novaehollandiae');
insert into pet (name, animal, race) values ('Rébecca', 'Owl, white-browed', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Örjan', 'Serval', 'Felis serval');
insert into pet (name, animal, race) values ('Åsa', 'Lesser flamingo', 'Phoeniconaias minor');
insert into pet (name, animal, race) values ('Léana', 'Alligator, american', 'Alligator mississippiensis');
insert into pet (name, animal, race) values ('Zhì', 'European badger', 'Meles meles');
insert into pet (name, animal, race) values ('Esbjörn', 'Black-capped capuchin', 'Cebus apella');
insert into pet (name, animal, race) values ('Estée', 'Eastern white pelican', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Léonie', 'Opossum, american virginia', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Mélia', 'Booby, blue-faced', 'Sula dactylatra');
insert into pet (name, animal, race) values ('Andrée', 'Tawny frogmouth', 'Podargus strigoides');
insert into pet (name, animal, race) values ('Bérangère', 'Beisa oryx', 'Oryx gazella');
insert into pet (name, animal, race) values ('Åke', 'Heron, black-crowned night', 'Nycticorax nycticorax');
insert into pet (name, animal, race) values ('Bérangère', 'Snake, western patch-nosed', 'Salvadora hexalepis');
insert into pet (name, animal, race) values ('Lén', 'Weaver, chestnut', 'Ploceus rubiginosus');
insert into pet (name, animal, race) values ('Vénus', 'Black rhinoceros', 'Diceros bicornis');
insert into pet (name, animal, race) values ('Thérèse', 'Crake, african black', 'Limnocorax flavirostra');
insert into pet (name, animal, race) values ('Gisèle', 'Blue and gold macaw', 'Ara ararauna');
insert into pet (name, animal, race) values ('Táng', 'White-browed owl', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Esbjörn', 'Waterbuck, defassa', 'Kobus defassa');
insert into pet (name, animal, race) values ('Naéva', 'Jungle cat', 'Felis chaus');
insert into pet (name, animal, race) values ('Maïté', 'Python (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Léonore', 'Lion, southern sea', 'Otaria flavescens');
insert into pet (name, animal, race) values ('Kévina', 'Hudsonian godwit', 'Limosa haemastica');
insert into pet (name, animal, race) values ('Angèle', 'Otter, cape clawless', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Dafnée', 'Zebra, plains', 'Equus burchelli');
insert into pet (name, animal, race) values ('Séverine', 'Turtle, eastern box', 'Terrapene carolina');
insert into pet (name, animal, race) values ('Stéphanie', 'Black-backed jackal', 'Canis mesomelas');
insert into pet (name, animal, race) values ('Célia', 'Gecko, tokay', 'Gekko gecko');
insert into pet (name, animal, race) values ('Jú', 'Common goldeneye', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Béatrice', 'Mynah, indian', 'Acridotheres tristis');
insert into pet (name, animal, race) values ('Méthode', 'Warthog', 'Phacochoerus aethiopus');
insert into pet (name, animal, race) values ('Hélèna', 'Stick insect', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Bérengère', 'Grouse, greater sage', 'Centrocercus urophasianus');
insert into pet (name, animal, race) values ('Séverine', 'Common shelduck', 'Tadorna tadorna');
insert into pet (name, animal, race) values ('Renée', 'Curlew, black', 'Haematopus ater');
insert into pet (name, animal, race) values ('Noëlla', 'Horned rattlesnake', 'Crotalus cerastes');
insert into pet (name, animal, race) values ('Håkan', 'Starling, superb', 'Lamprotornis superbus');
insert into pet (name, animal, race) values ('Mégane', 'American bison', 'Bison bison');
insert into pet (name, animal, race) values ('Rachèle', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Åslög', 'Mocking cliffchat', 'Thamnolaea cinnmomeiventris');
insert into pet (name, animal, race) values ('Anaé', 'Capybara', 'Hydrochoerus hydrochaeris');
insert into pet (name, animal, race) values ('Dù', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Pénélope', 'Gonolek, burchell''s', 'Laniaurius atrococcineus');
insert into pet (name, animal, race) values ('Valérie', 'Black-capped chickadee', 'Parus atricapillus');
insert into pet (name, animal, race) values ('Géraldine', 'Goldeneye, common', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Célia', 'Fowl, helmeted guinea', 'Numida meleagris');
insert into pet (name, animal, race) values ('Sòng', 'Tokay gecko', 'Gekko gecko');
insert into pet (name, animal, race) values ('Görel', 'Bush dog', 'Speothos vanaticus');
insert into pet (name, animal, race) values ('Adélaïde', 'Common mynah', 'Acridotheres tristis');
insert into pet (name, animal, race) values ('Valérie', 'Bear, black', 'Ursus americanus');
insert into pet (name, animal, race) values ('Bérangère', 'Thirteen-lined squirrel', 'Spermophilus tridecemlineatus');
insert into pet (name, animal, race) values ('Erwéi', 'Small-toothed palm civet', 'Arctogalidia trivirgata');
insert into pet (name, animal, race) values ('Östen', 'African snake (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Léone', 'Small-toothed palm civet', 'Arctogalidia trivirgata');
insert into pet (name, animal, race) values ('Yénora', 'Stanley bustard', 'Neotis denhami');
insert into pet (name, animal, race) values ('Ruò', 'Mongoose, eastern dwarf', 'Helogale undulata');
insert into pet (name, animal, race) values ('Intéressant', 'Dromedary camel', 'Camelus dromedarius');
insert into pet (name, animal, race) values ('Maëly', 'European spoonbill', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Naéva', 'Hanuman langur', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Eléonore', 'Emerald green tree boa', 'Boa caninus');
insert into pet (name, animal, race) values ('Östen', 'Kori bustard', 'Choriotis kori');
insert into pet (name, animal, race) values ('Thérèse', 'Greylag goose', 'Anser anser');
insert into pet (name, animal, race) values ('Maïté', 'Currasow (unidentified)', 'Crax sp.');
insert into pet (name, animal, race) values ('Maëlys', 'Hornbill, southern ground', 'Bucorvus leadbeateri');
insert into pet (name, animal, race) values ('Valérie', 'Bleu, blue-breasted cordon', 'Uraeginthus angolensis');
insert into pet (name, animal, race) values ('Léonie', 'Laughing kookaburra', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Gösta', 'Tortoise, indian star', 'Geochelone elegans');
insert into pet (name, animal, race) values ('Béatrice', 'Great skua', 'Catharacta skua');
insert into pet (name, animal, race) values ('Göran', 'Hedgehog, south african', 'Erinaceus frontalis');
insert into pet (name, animal, race) values ('Maïlis', 'White-winged black tern', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Géraldine', 'Heron, green-backed', 'Butorides striatus');
insert into pet (name, animal, race) values ('Yú', 'Dama wallaby', 'Macropus eugenii');
insert into pet (name, animal, race) values ('Håkan', 'Indian jackal', 'Canis aureus');
insert into pet (name, animal, race) values ('Lauréna', 'Skua, long-tailed', 'Stercorarius longicausus');
insert into pet (name, animal, race) values ('Eloïse', 'Fox, pampa gray', 'Pseudalopex gymnocercus');
insert into pet (name, animal, race) values ('Vérane', 'Gazelle, thomson''s', 'Gazella thompsonii');
insert into pet (name, animal, race) values ('Cléopatre', 'Red-billed toucan', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Stévina', 'African fish eagle', 'Haliaetus vocifer');
insert into pet (name, animal, race) values ('Maëlys', 'Dragon, asian water', 'Physignathus cocincinus');
insert into pet (name, animal, race) values ('Lài', 'Lizard, collared', 'Crotaphytus collaris');
insert into pet (name, animal, race) values ('Angélique', 'Stanley crane', 'Anthropoides paradisea');
insert into pet (name, animal, race) values ('Fèi', 'Langur, gray', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Cléopatre', 'White-fronted capuchin', 'Cebus albifrons');
insert into pet (name, animal, race) values ('Åke', 'Lesser mouse lemur', 'Microcebus murinus');
insert into pet (name, animal, race) values ('Cléa', 'Rabbit, eastern cottontail', 'Sylvilagus floridanus');
insert into pet (name, animal, race) values ('Mylène', 'Rufous tree pie', 'Dendrocitta vagabunda');
insert into pet (name, animal, race) values ('Régine', 'Kookaburra, laughing', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Judicaël', 'Black-capped chickadee', 'Parus atricapillus');
insert into pet (name, animal, race) values ('Lóng', 'Macaw, scarlet', 'Ara macao');
insert into pet (name, animal, race) values ('Léandre', 'Sunbird, lesser double-collared', 'Nectarinia chalybea');
insert into pet (name, animal, race) values ('Nadège', 'Steenbok', 'Raphicerus campestris');
insert into pet (name, animal, race) values ('Séréna', 'Bat-eared fox', 'Otocyon megalotis');
insert into pet (name, animal, race) values ('Nélie', 'Dabchick', 'Tachybaptus ruficollis');
insert into pet (name, animal, race) values ('Maëlle', 'Wolf, timber', 'Canis lupus lycaon');
insert into pet (name, animal, race) values ('Lèi', 'Sheep, stone', 'Ovis dalli stonei');
insert into pet (name, animal, race) values ('Lóng', 'Western palm tanager (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Åke', 'Chimpanzee', 'Pan troglodytes');
insert into pet (name, animal, race) values ('Michèle', 'Bald eagle', 'Haliaeetus leucocephalus');
insert into pet (name, animal, race) values ('Hélène', 'Tammar wallaby', 'Macropus eugenii');
insert into pet (name, animal, race) values ('Laurélie', 'Curve-billed thrasher', 'Toxostoma curvirostre');
insert into pet (name, animal, race) values ('Naéva', 'Australian pelican', 'Pelecanus conspicillatus');
insert into pet (name, animal, race) values ('Célia', 'Water monitor', 'Varanus salvator');
insert into pet (name, animal, race) values ('Maïté', 'Phascogale, red-tailed', 'Phascogale calura');
insert into pet (name, animal, race) values ('Noémie', 'Baboon, savanna', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Gaétane', 'Russian dragonfly', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Léana', 'Bandicoot, long-nosed', 'Perameles nasuta');
insert into pet (name, animal, race) values ('Måns', 'Blue racer', 'Coluber constrictor foxii');
insert into pet (name, animal, race) values ('Eloïse', 'Bustard, stanley', 'Neotis denhami');
insert into pet (name, animal, race) values ('Maëlle', 'Booby, blue-footed', 'Sula nebouxii');
insert into pet (name, animal, race) values ('Athéna', 'Southern black-backed gull', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Sélène', 'Rock dove', 'Columba livia');
insert into pet (name, animal, race) values ('Personnalisée', 'Baboon, yellow', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Måns', 'Tammar wallaby', 'Macropus eugenii');
insert into pet (name, animal, race) values ('Mélinda', 'Long-tailed skua', 'Stercorarius longicausus');
insert into pet (name, animal, race) values ('Táng', 'Starling, cape', 'Lamprotornis nitens');
insert into pet (name, animal, race) values ('Célestine', 'Ground legaan', 'Varanus sp.');
insert into pet (name, animal, race) values ('Séréna', 'Emerald green tree boa', 'Boa caninus');
insert into pet (name, animal, race) values ('Marie-françoise', 'Black-footed ferret', 'Mustela nigripes');
insert into pet (name, animal, race) values ('Michèle', 'Tortoise, asian foreset', 'Manouria emys');
insert into pet (name, animal, race) values ('Thérèse', 'Crab-eating raccoon', 'Procyon cancrivorus');
insert into pet (name, animal, race) values ('Torbjörn', 'Ibis, sacred', 'Threskionis aethiopicus');
insert into pet (name, animal, race) values ('Eloïse', 'Downy woodpecker', 'Picoides pubescens');
insert into pet (name, animal, race) values ('André', 'Laughing kookaburra', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Kévina', 'Flamingo, greater', 'Phoenicopterus ruber');
insert into pet (name, animal, race) values ('Renée', 'Booby, blue-faced', 'Sula dactylatra');
insert into pet (name, animal, race) values ('Yóu', 'Water legaan', 'Varanus salvator');
insert into pet (name, animal, race) values ('Frédérique', 'Heron, little', 'Butorides striatus');
insert into pet (name, animal, race) values ('Laurélie', 'Pied butcher bird', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Kù', 'Deer, swamp', 'Cervus duvauceli');
insert into pet (name, animal, race) values ('Aimée', 'Sloth bear', 'Melursus ursinus');
insert into pet (name, animal, race) values ('Stéphanie', 'Pine siskin', 'Carduelis pinus');
insert into pet (name, animal, race) values ('Solène', 'Cattle egret', 'Bubulcus ibis');
insert into pet (name, animal, race) values ('Séverine', 'Common langur', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Styrbjörn', 'Butterfly, tropical buckeye', 'Junonia genoveua');
insert into pet (name, animal, race) values ('Gösta', 'Lizard, giant girdled', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Mélodie', 'Gazer, sun', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Cunégonde', 'Iguana, land', 'Conolophus subcristatus');
insert into pet (name, animal, race) values ('Cécilia', 'Short-beaked echidna', 'Tachyglossus aculeatus');
insert into pet (name, animal, race) values ('Tán', 'Azara''s zorro', 'Pseudalopex gymnocercus');
insert into pet (name, animal, race) values ('Vérane', 'Jackal, golden', 'Canis aureus');
insert into pet (name, animal, race) values ('Kévina', 'Sun gazer', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Ruò', 'Whale, southern right', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Mélina', 'Cormorant, great', 'Phalacrocorax carbo');
insert into pet (name, animal, race) values ('Véronique', 'Monkey, bleeding heart', 'Theropithecus gelada');
insert into pet (name, animal, race) values ('Maëline', 'Water legaan', 'Varanus salvator');
insert into pet (name, animal, race) values ('Maëlla', 'Red-billed toucan', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Maïwenn', 'Fairy penguin', 'Eudyptula minor');
insert into pet (name, animal, race) values ('Lén', 'Little brown bat', 'Myotis lucifugus');
insert into pet (name, animal, race) values ('Nélie', 'Giant heron', 'Ardea golieth');
insert into pet (name, animal, race) values ('Edmée', 'Tern, white-winged black', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Valérie', 'Hare, arctic', 'Lepus arcticus');
insert into pet (name, animal, race) values ('Géraldine', 'Baleen whale', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Táng', 'Otter, african clawless', 'Aonyx capensis');
insert into pet (name, animal, race) values ('Félicie', 'Badger, eurasian', 'Meles meles');
insert into pet (name, animal, race) values ('Audréanne', 'Lion, galapagos sea', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Méryl', 'Cat, miner''s', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Lorène', 'Stork, black-necked', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Rachèle', 'Brazilian tapir', 'Tapirus terrestris');
insert into pet (name, animal, race) values ('Ráo', 'Brush-tailed rat kangaroo', 'Bettongia penicillata');
insert into pet (name, animal, race) values ('Dafnée', 'Ring-tailed possum', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Tú', 'Four-striped grass mouse', 'Rhabdomys pumilio');
insert into pet (name, animal, race) values ('Andrée', 'Ferret, black-footed', 'Mustela nigripes');
insert into pet (name, animal, race) values ('Nuó', 'Feral rock pigeon', 'Columba livia');
insert into pet (name, animal, race) values ('Björn', 'Raccoon, common', 'Procyon lotor');
insert into pet (name, animal, race) values ('Amélie', 'Jungle cat', 'Felis chaus');
insert into pet (name, animal, race) values ('Crééz', 'Glossy starling (unidentified)', 'Lamprotornis sp.');
insert into pet (name, animal, race) values ('Athéna', 'Anaconda (unidentified)', 'Eunectes sp.');
insert into pet (name, animal, race) values ('Cécilia', 'Avocet, pied', 'Recurvirostra avosetta');
insert into pet (name, animal, race) values ('Angélique', 'Grizzly bear', 'Ursus arctos');
insert into pet (name, animal, race) values ('Amélie', 'Baboon, savanna', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Personnalisée', 'Coyote', 'Canis latrans');
insert into pet (name, animal, race) values ('Clélia', 'Timber wolf', 'Canis lupus lycaon');
insert into pet (name, animal, race) values ('Cléa', 'Rhea, greater', 'Rhea americana');
insert into pet (name, animal, race) values ('Annotée', 'California sea lion', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Solène', 'Eurasian badger', 'Meles meles');
insert into pet (name, animal, race) values ('Anaé', 'Northern phalarope', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Marie-hélène', 'Uinta ground squirrel', 'Spermophilus armatus');
insert into pet (name, animal, race) values ('Marlène', 'Bunting, crested', 'Melophus lathami');
insert into pet (name, animal, race) values ('Pélagie', 'Black-tailed prairie dog', 'Cynomys ludovicianus');
insert into pet (name, animal, race) values ('Félicie', 'Waxbill, black-cheeked', 'Estrilda erythronotos');
insert into pet (name, animal, race) values ('Pélagie', 'Crane, sandhill', 'Grus canadensis');
insert into pet (name, animal, race) values ('Stéphanie', 'Grebe, little', 'Tachybaptus ruficollis');
insert into pet (name, animal, race) values ('Alizée', 'Drongo, fork-tailed', 'Dicrurus adsimilis');
insert into pet (name, animal, race) values ('Sélène', 'Hawk-eagle, crowned', 'Spizaetus coronatus');
insert into pet (name, animal, race) values ('Camélia', 'American Virginia opossum', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Pénélope', 'Little brown dove', 'Streptopelia senegalensis');
insert into pet (name, animal, race) values ('Magdalène', 'Leopard, indian', 'Panthera pardus');
insert into pet (name, animal, race) values ('Tú', 'Whale, long-finned pilot', 'Globicephala melas');
insert into pet (name, animal, race) values ('Méghane', 'Fox, blue', 'Alopex lagopus');
insert into pet (name, animal, race) values ('Régine', 'Parakeet, rose-ringed', 'Psittacula krameri');
insert into pet (name, animal, race) values ('Lài', 'Goanna lizard', 'Varanus sp.');
insert into pet (name, animal, race) values ('Athéna', 'Barasingha deer', 'Cervus duvauceli');
insert into pet (name, animal, race) values ('Méline', 'Arctic tern', 'Sterna paradisaea');
insert into pet (name, animal, race) values ('Séréna', 'Finch, common melba', 'Pytilia melba');
insert into pet (name, animal, race) values ('Maëlla', 'Silver-backed jackal', 'Canis mesomelas');
insert into pet (name, animal, race) values ('Séréna', 'Beaver, eurasian', 'Castor fiber');
insert into pet (name, animal, race) values ('Judicaël', 'Red-headed woodpecker', 'Melanerpes erythrocephalus');
insert into pet (name, animal, race) values ('Léone', 'Javan gold-spotted mongoose', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Danièle', 'Swallow (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Daphnée', 'Boar, wild', 'Sus scrofa');
insert into pet (name, animal, race) values ('Cléopatre', 'Hippopotamus', 'Hippopotamus amphibius');
insert into pet (name, animal, race) values ('Lorène', 'Hawk, ferruginous', 'Buteo regalis');
insert into pet (name, animal, race) values ('Hélèna', 'Waxbill, violet-eared', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Vérane', 'Lion, asian', 'Panthera leo persica');
insert into pet (name, animal, race) values ('Erwéi', 'Roseate cockatoo', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Pélagie', 'Caracal', 'Felis caracal');
insert into pet (name, animal, race) values ('Cunégonde', 'Weaver, red-billed buffalo', 'Bubalornis niger');
insert into pet (name, animal, race) values ('Françoise', 'Eleven-banded armadillo (unidentified)', 'Cabassous sp.');
insert into pet (name, animal, race) values ('Mélia', 'Ferruginous hawk', 'Buteo regalis');
insert into pet (name, animal, race) values ('Eliès', 'Magistrate black colobus', 'Colobus guerza');
insert into pet (name, animal, race) values ('Intéressant', 'Screamer, crested', 'Chauna torquata');
insert into pet (name, animal, race) values ('Maëlyss', 'Glider, feathertail', 'Acrobates pygmaeus');
insert into pet (name, animal, race) values ('Geneviève', 'White-fronted capuchin', 'Cebus albifrons');
insert into pet (name, animal, race) values ('Lucrèce', 'Common palm civet', 'Paradoxurus hermaphroditus');
insert into pet (name, animal, race) values ('Méline', 'Bush dog', 'Speothos vanaticus');
insert into pet (name, animal, race) values ('Publicité', 'Nubian bee-eater', 'Merops nubicus');
insert into pet (name, animal, race) values ('Adèle', 'Lion, south american sea', 'Otaria flavescens');
insert into pet (name, animal, race) values ('Intéressant', 'Cat, kaffir', 'Felis silvestris lybica');
insert into pet (name, animal, race) values ('Garçon', 'Columbian rainbow boa', 'Epicrates cenchria maurus');
insert into pet (name, animal, race) values ('Marie-noël', 'Chuckwalla', 'Sauromalus obesus');
insert into pet (name, animal, race) values ('Thérèse', 'Lion, galapagos sea', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Laurélie', 'Canadian river otter', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Håkan', 'Shrike, common boubou', 'Laniarius ferrugineus');
insert into pet (name, animal, race) values ('Léandre', 'Gulls (unidentified)', 'Larus sp.');
insert into pet (name, animal, race) values ('Naëlle', 'Carpet snake', 'Morelia spilotes variegata');
insert into pet (name, animal, race) values ('Östen', 'Bird, black-throated butcher', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Zoé', 'Heron, yellow-crowned night', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Åke', 'Gelada baboon', 'Theropithecus gelada');
insert into pet (name, animal, race) values ('Laïla', 'Tasmanian devil', 'Sarcophilus harrisii');
insert into pet (name, animal, race) values ('Andréanne', 'Antechinus, brown', 'Antechinus flavipes');
insert into pet (name, animal, race) values ('Audréanne', 'Greater rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Anaëlle', 'Barbet, black-collared', 'Lybius torquatus');
insert into pet (name, animal, race) values ('Illustrée', 'Trotter, lily', 'Actophilornis africanus');
insert into pet (name, animal, race) values ('Maïté', 'Lesser double-collared sunbird', 'Nectarinia chalybea');
insert into pet (name, animal, race) values ('Görel', 'Black-necked stork', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Loïca', 'Francolin, swainson''s', 'Francolinus swainsonii');
insert into pet (name, animal, race) values ('Lucrèce', 'Blue crane', 'Anthropoides paradisea');
insert into pet (name, animal, race) values ('Publicité', 'European spoonbill', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Ruò', 'Pig-tailed macaque', 'Macaca nemestrina');
insert into pet (name, animal, race) values ('Cécilia', 'Agile wallaby', 'Macropus agilis');
insert into pet (name, animal, race) values ('Kévina', 'Ring-tailed gecko', 'Cyrtodactylus louisiadensis');
insert into pet (name, animal, race) values ('Andréanne', 'Sunbird, lesser double-collared', 'Nectarinia chalybea');
insert into pet (name, animal, race) values ('Tán', 'Antelope, sable', 'Hippotragus niger');
insert into pet (name, animal, race) values ('Judicaël', 'Cat, long-tailed spotted', 'Felis wiedi or Leopardus weidi');
insert into pet (name, animal, race) values ('Naéva', 'Emerald green tree boa', 'Boa caninus');
insert into pet (name, animal, race) values ('Clémence', 'Cape wild cat', 'Felis libyca');
insert into pet (name, animal, race) values ('Véronique', 'Jackal, asiatic', 'Canis aureus');
insert into pet (name, animal, race) values ('Tú', 'Grison', 'Galictis vittata');
insert into pet (name, animal, race) values ('Audréanne', 'Grey-footed squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Béatrice', 'Whale, baleen', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Yénora', 'Cook''s tree boa', 'Corallus hortulanus cooki');
insert into pet (name, animal, race) values ('Gaétane', 'Rhinoceros, black', 'Diceros bicornis');
insert into pet (name, animal, race) values ('Ophélie', 'Malagasy ground boa', 'Acrantophis madagascariensis');
insert into pet (name, animal, race) values ('Cléa', 'Tyrant flycatcher', 'Myiarchus tuberculifer');
insert into pet (name, animal, race) values ('Andréa', 'Cliffchat, mocking', 'Thamnolaea cinnmomeiventris');
insert into pet (name, animal, race) values ('Eloïse', 'Emerald green tree boa', 'Boa caninus');
insert into pet (name, animal, race) values ('Méryl', 'Dolphin, striped', 'Stenella coeruleoalba');
insert into pet (name, animal, race) values ('Dorothée', 'Water moccasin', 'Agkistrodon piscivorus');
insert into pet (name, animal, race) values ('Pénélope', 'Red sheep', 'Ovis ammon');
insert into pet (name, animal, race) values ('Eléonore', 'Sacred ibis', 'Threskionis aethiopicus');
insert into pet (name, animal, race) values ('Thérèse', 'Black curlew', 'Haematopus ater');
insert into pet (name, animal, race) values ('Béatrice', 'Shrike, crimson-breasted', 'Laniaurius atrococcineus');
insert into pet (name, animal, race) values ('Vérane', 'Brown antechinus', 'Antechinus flavipes');
insert into pet (name, animal, race) values ('Uò', 'Blue wildebeest', 'Connochaetus taurinus');
insert into pet (name, animal, race) values ('André', 'Bonnet macaque', 'Macaca radiata');
insert into pet (name, animal, race) values ('Amélie', 'Rattlesnake, dusky', 'Crotalus triseriatus');
insert into pet (name, animal, race) values ('Laurène', 'Asian water dragon', 'Physignathus cocincinus');
insert into pet (name, animal, race) values ('Styrbjörn', 'Oriental white-backed vulture', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('Maïté', 'Owl, great horned', 'Bubo virginianus');
insert into pet (name, animal, race) values ('Miléna', 'Amazon parrot (unidentified)', 'Amazona sp.');
insert into pet (name, animal, race) values ('Frédérique', 'Macaque, pig-tailed', 'Macaca nemestrina');
insert into pet (name, animal, race) values ('Bécassine', 'Shrike, common boubou', 'Laniarius ferrugineus');
insert into pet (name, animal, race) values ('Océane', 'Cow, scottish highland', 'Bos taurus');
insert into pet (name, animal, race) values ('Béatrice', 'Green-backed heron', 'Butorides striatus');
insert into pet (name, animal, race) values ('Océane', 'Boar, wild', 'Sus scrofa');
insert into pet (name, animal, race) values ('Dorothée', 'Golden brush-tailed possum', 'Trichosurus vulpecula');
insert into pet (name, animal, race) values ('Maïwenn', 'Bonnet macaque', 'Macaca radiata');
insert into pet (name, animal, race) values ('Andréa', 'Gull, pacific', 'Gabianus pacificus');
insert into pet (name, animal, race) values ('Magdalène', 'Black-throated butcher bird', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Adélie', 'Little cormorant', 'Phalacrocorax niger');
insert into pet (name, animal, race) values ('Noémie', 'Sportive lemur', 'Lepilemur rufescens');
insert into pet (name, animal, race) values ('Irène', 'Gulls (unidentified)', 'Larus sp.');
insert into pet (name, animal, race) values ('Fèi', 'Otter, small-clawed', 'Aonyx cinerea');
insert into pet (name, animal, race) values ('Maïly', 'Hartebeest, red', 'Alcelaphus buselaphus caama');
insert into pet (name, animal, race) values ('Joséphine', 'Black-throated cardinal', 'Paroaria gularis');
insert into pet (name, animal, race) values ('Gösta', 'Spectacled caiman', 'Caiman crocodilus');
insert into pet (name, animal, race) values ('Loïc', 'Praying mantis (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Irène', 'Little brown dove', 'Streptopelia senegalensis');
insert into pet (name, animal, race) values ('Rachèle', 'Crested porcupine', 'Hystrix cristata');
insert into pet (name, animal, race) values ('Simplifiés', 'Spurfowl, yellow-necked', 'Francolinus leucoscepus');
insert into pet (name, animal, race) values ('Estée', 'Snake, carpet', 'Morelia spilotes variegata');
insert into pet (name, animal, race) values ('Garçon', 'Nutcracker, clark''s', 'Nucifraga columbiana');
insert into pet (name, animal, race) values ('Cunégonde', 'Eagle, bateleur', 'Terathopius ecaudatus');
insert into pet (name, animal, race) values ('Régine', 'Stork, white', 'Ciconia ciconia');
insert into pet (name, animal, race) values ('Uò', 'Dove, white-winged', 'Zenaida asiatica');
insert into pet (name, animal, race) values ('Göran', 'African skink', 'Mabuya spilogaster');
insert into pet (name, animal, race) values ('Eléonore', 'Coatimundi, white-nosed', 'Nasua narica');
insert into pet (name, animal, race) values ('Edmée', 'Madagascar hawk owl', 'Ninox superciliaris');
insert into pet (name, animal, race) values ('Maïté', 'Nelson ground squirrel', 'Ammospermophilus nelsoni');
insert into pet (name, animal, race) values ('Camélia', 'Civet, small-toothed palm', 'Arctogalidia trivirgata');
insert into pet (name, animal, race) values ('Alizée', 'Deer, barasingha', 'Cervus duvauceli');
insert into pet (name, animal, race) values ('Célia', 'Kangaroo, brush-tailed rat', 'Bettongia penicillata');
insert into pet (name, animal, race) values ('Gisèle', 'Gull, dusky', 'Larus fuliginosus');
insert into pet (name, animal, race) values ('Åke', 'Puna ibis', 'Plegadis ridgwayi');
insert into pet (name, animal, race) values ('Méghane', 'Pig-tailed macaque', 'Macaca nemestrina');
insert into pet (name, animal, race) values ('Loïs', 'Egret, snowy', 'Egretta thula');
insert into pet (name, animal, race) values ('Amélie', 'Blesbok', 'Damaliscus dorcas');
insert into pet (name, animal, race) values ('Anaël', 'Bat, little brown', 'Myotis lucifugus');
insert into pet (name, animal, race) values ('Maëlys', 'Cape wild cat', 'Felis libyca');
insert into pet (name, animal, race) values ('Loïc', 'Bandicoot, short-nosed', 'Isoodon obesulus');
insert into pet (name, animal, race) values ('Zhì', 'Blue racer', 'Coluber constrictor foxii');
insert into pet (name, animal, race) values ('Håkan', 'Goose, snow', 'Anser caerulescens');
insert into pet (name, animal, race) values ('Daphnée', 'African bush squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Méng', 'Penguin, magellanic', 'Spheniscus magellanicus');
insert into pet (name, animal, race) values ('Marie-noël', 'Barbet, crested', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Illustrée', 'White-mantled colobus', 'Colobus guerza');
insert into pet (name, animal, race) values ('Edmée', 'Lemur, brown', 'Lemur fulvus');
insert into pet (name, animal, race) values ('Mélina', 'Rose-ringed parakeet', 'Psittacula krameri');
insert into pet (name, animal, race) values ('Erwéi', 'Palm squirrel', 'Funambulus pennati');
insert into pet (name, animal, race) values ('Mélina', 'Baboon, chacma', 'Papio ursinus');
insert into pet (name, animal, race) values ('Loïca', 'Grouse, sage', 'Centrocercus urophasianus');
insert into pet (name, animal, race) values ('Aloïs', 'Lemur, ring-tailed', 'Lemur catta');
insert into pet (name, animal, race) values ('Maïté', 'Blue fox', 'Alopex lagopus');
insert into pet (name, animal, race) values ('Crééz', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('André', 'Blacksmith plover', 'Vanellus armatus');
insert into pet (name, animal, race) values ('Loïca', 'Levaillant''s barbet', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Léone', 'Trotter, lily', 'Actophilornis africanus');
insert into pet (name, animal, race) values ('Kù', 'Darwin ground finch (unidentified)', 'Geospiza sp.');
insert into pet (name, animal, race) values ('Frédérique', 'American marten', 'Martes americana');
insert into pet (name, animal, race) values ('Aloïs', 'Flamingo, roseat', 'Phoenicopterus ruber');
insert into pet (name, animal, race) values ('Ruì', 'Lion, galapagos sea', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Sélène', 'Mudskipper (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Torbjörn', 'Southern tamandua', 'Tamandua tetradactyla');
insert into pet (name, animal, race) values ('Yáo', 'Tiger snake', 'Notechis semmiannulatus');
insert into pet (name, animal, race) values ('Loïc', 'Robin, white-throated', 'Irania gutteralis');
insert into pet (name, animal, race) values ('Thérèse', 'Turkey, common', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Kallisté', 'Cormorant, king', 'Phalacrocorax albiventer');
insert into pet (name, animal, race) values ('Laïla', 'Superb starling', 'Lamprotornis superbus');
insert into pet (name, animal, race) values ('Anaël', 'Blacksmith plover', 'Vanellus armatus');
insert into pet (name, animal, race) values ('Simplifiés', 'Wild turkey', 'Meleagris gallopavo');
insert into pet (name, animal, race) values ('Aloïs', 'Little heron', 'Butorides striatus');
insert into pet (name, animal, race) values ('Gisèle', 'Gambel''s quail', 'Callipepla gambelii');
insert into pet (name, animal, race) values ('Médiamass', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Gösta', 'Racer snake', 'Coluber constrictor');
insert into pet (name, animal, race) values ('Nélie', 'Arctic ground squirrel', 'Spermophilus parryii');
insert into pet (name, animal, race) values ('Lorène', 'Bear, sloth', 'Melursus ursinus');
insert into pet (name, animal, race) values ('Loïc', 'Long-nosed bandicoot', 'Perameles nasuta');
insert into pet (name, animal, race) values ('Joséphine', 'Glider, feathertail', 'Acrobates pygmaeus');
insert into pet (name, animal, race) values ('Marie-ève', 'Crow, american', 'Corvus brachyrhynchos');
insert into pet (name, animal, race) values ('Åslög', 'Cliffchat, mocking', 'Thamnolaea cinnmomeiventris');
insert into pet (name, animal, race) values ('Mà', 'Black-faced kangaroo', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Lauréna', 'Crane, sandhill', 'Grus canadensis');
insert into pet (name, animal, race) values ('Tú', 'Land iguana', 'Conolophus subcristatus');
insert into pet (name, animal, race) values ('Estée', 'Squirrel, thirteen-lined', 'Spermophilus tridecemlineatus');
insert into pet (name, animal, race) values ('Mégane', 'Prehensile-tailed porcupine', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Réservés', 'Squirrel, uinta ground', 'Spermophilus armatus');
insert into pet (name, animal, race) values ('Esbjörn', 'White-winged black tern', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Félicie', 'Thrasher, curve-billed', 'Toxostoma curvirostre');
insert into pet (name, animal, race) values ('Rébecca', 'Russian dragonfly', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Annotée', 'Common green iguana', 'Iguana iguana');
insert into pet (name, animal, race) values ('Dà', 'Phalarope, northern', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Göran', 'Jungle cat', 'Felis chaus');
insert into pet (name, animal, race) values ('Judicaël', 'Reindeer', 'Rangifer tarandus');
insert into pet (name, animal, race) values ('Camélia', 'Vulture, egyptian', 'Neophron percnopterus');
insert into pet (name, animal, race) values ('Gösta', 'Coqui francolin', 'Francolinus coqui');
insert into pet (name, animal, race) values ('Gösta', 'Antelope, sable', 'Hippotragus niger');
insert into pet (name, animal, race) values ('Lén', 'Common ringtail', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Maëlla', 'Crested barbet', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Dorothée', 'Jaguarundi', 'Felis yagouaroundi');
insert into pet (name, animal, race) values ('Dà', 'Rat, white-faced tree', 'Echimys chrysurus');
insert into pet (name, animal, race) values ('Marie-ève', 'Pheasant, common', 'Phasianus colchicus');
insert into pet (name, animal, race) values ('Dafnée', 'Least chipmunk', 'Eutamias minimus');
insert into pet (name, animal, race) values ('Björn', 'Gazer, sun', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Lyséa', 'Kangaroo, western grey', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Maëlle', 'Shelduck, common', 'Tadorna tadorna');
insert into pet (name, animal, race) values ('Bérénice', 'Smith''s bush squirrel', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Mélys', 'Beaver, eurasian', 'Castor fiber');
insert into pet (name, animal, race) values ('Bénédicte', 'Mourning collared dove', 'Streptopelia decipiens');
insert into pet (name, animal, race) values ('Inès', 'Lion, california sea', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Naëlle', 'Yak', 'Bos mutus');
insert into pet (name, animal, race) values ('Maëly', 'Koala', 'Phascolarctos cinereus');
insert into pet (name, animal, race) values ('Françoise', 'Puffin, horned', 'Fratercula corniculata');
insert into pet (name, animal, race) values ('Thérèsa', 'Mexican boa', 'Boa constrictor mexicana');
insert into pet (name, animal, race) values ('Clélia', 'Nyala', 'Tragelaphus angasi');
insert into pet (name, animal, race) values ('Andréa', 'Ornate rock dragon', 'Ctenophorus ornatus');
insert into pet (name, animal, race) values ('Erwéi', 'Aardwolf', 'Proteles cristatus');
insert into pet (name, animal, race) values ('Pò', 'Goose, knob-nosed', 'Sarkidornis melanotos');
insert into pet (name, animal, race) values ('Måns', 'Galapagos penguin', 'Spheniscus mendiculus');
insert into pet (name, animal, race) values ('Aí', 'Cat, jungle', 'Felis chaus');
insert into pet (name, animal, race) values ('Amélie', 'Stick insect', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Véronique', 'Yellow-headed caracara', 'Milvago chimachima');
insert into pet (name, animal, race) values ('Yú', 'Echidna, short-beaked', 'Tachyglossus aculeatus');
insert into pet (name, animal, race) values ('Mégane', 'Two-toed tree sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Maï', 'Booby, blue-footed', 'Sula nebouxii');
insert into pet (name, animal, race) values ('Médiamass', 'Magnificent frigate bird', 'Fregata magnificans');
insert into pet (name, animal, race) values ('Zhì', 'Sidewinder', 'Crotalus cerastes');
insert into pet (name, animal, race) values ('Mårten', 'Laughing kookaburra', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Gwenaëlle', 'Eastern box turtle', 'Terrapene carolina');
insert into pet (name, animal, race) values ('Marie-noël', 'Sloth, pale-throated three-toed', 'Bradypus tridactylus');
insert into pet (name, animal, race) values ('Dà', 'Greater kudu', 'Tragelaphus strepsiceros');
insert into pet (name, animal, race) values ('Eléonore', 'Rufous tree pie', 'Dendrocitta vagabunda');
insert into pet (name, animal, race) values ('Sòng', 'Egyptian goose', 'Alopochen aegyptiacus');
insert into pet (name, animal, race) values ('Maïwenn', 'Arctic ground squirrel', 'Spermophilus parryii');
insert into pet (name, animal, race) values ('Noémie', 'Dove, mourning collared', 'Streptopelia decipiens');
insert into pet (name, animal, race) values ('Maïwenn', 'Javan gold-spotted mongoose', 'Herpestes javanicus');
insert into pet (name, animal, race) values ('Laïla', 'Screamer, southern', 'Chauna torquata');
insert into pet (name, animal, race) values ('Cécile', 'Blue and yellow macaw', 'Ara ararauna');
insert into pet (name, animal, race) values ('Océanne', 'Legaan, Monitor (unidentified)', 'Varanus sp.');
insert into pet (name, animal, race) values ('Naéva', 'Eastern quoll', 'Dasyurus viverrinus');
insert into pet (name, animal, race) values ('Marie-françoise', 'Chuckwalla', 'Sauromalus obesus');
insert into pet (name, animal, race) values ('Jú', 'Booby, blue-footed', 'Sula nebouxii');
insert into pet (name, animal, race) values ('Camélia', 'Four-horned antelope', 'Tetracerus quadricornis');
insert into pet (name, animal, race) values ('Almérinda', 'Goldeneye, barrows', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Léana', 'Bat, little brown', 'Myotis lucifugus');
insert into pet (name, animal, race) values ('Maïté', 'Hoary marmot', 'Marmota caligata');
insert into pet (name, animal, race) values ('Lyséa', 'Rhea, greater', 'Rhea americana');
insert into pet (name, animal, race) values ('Cunégonde', 'Penguin, magellanic', 'Spheniscus magellanicus');
insert into pet (name, animal, race) values ('Thérèsa', 'Stork, yellow-billed', 'Mycteria ibis');
insert into pet (name, animal, race) values ('Göran', 'Emerald green tree boa', 'Boa caninus');
insert into pet (name, animal, race) values ('Maéna', 'Parakeet, rose-ringed', 'Psittacula krameri');
insert into pet (name, animal, race) values ('Estée', 'Common dolphin', 'Delphinus delphis');
insert into pet (name, animal, race) values ('Maëlle', 'Great horned owl', 'Bubo virginianus');
insert into pet (name, animal, race) values ('Marlène', 'Bustard, denham''s', 'Neotis denhami');
insert into pet (name, animal, race) values ('Josée', 'Flicker, campo', 'Colaptes campestroides');
insert into pet (name, animal, race) values ('Réservés', 'Worm snake (unidentified)', 'Carphophis sp.');
insert into pet (name, animal, race) values ('Stéphanie', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Noémie', 'Red-shouldered glossy starling', 'Lamprotornis nitens');
insert into pet (name, animal, race) values ('Håkan', 'Duck, white-faced whistling', 'Dendrocygna viduata');
insert into pet (name, animal, race) values ('Marie-noël', 'Galapagos dove', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Lèi', 'European badger', 'Meles meles');
insert into pet (name, animal, race) values ('Eléa', 'Radiated tortoise', 'Geochelone radiata');
insert into pet (name, animal, race) values ('Yè', 'Seal, harbor', 'Phoca vitulina');
insert into pet (name, animal, race) values ('Estée', 'Lourie, grey', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Ráo', 'Rhinoceros, white', 'Ceratotherium simum');
insert into pet (name, animal, race) values ('Léone', 'Yellow-billed hornbill', 'Tockus flavirostris');
insert into pet (name, animal, race) values ('Mà', 'Pine siskin', 'Carduelis pinus');
insert into pet (name, animal, race) values ('Maëlys', 'Red-billed toucan', 'Ramphastos tucanus');
insert into pet (name, animal, race) values ('Salomé', 'Woylie', 'Bettongia penicillata');
insert into pet (name, animal, race) values ('Célia', 'Black-throated cardinal', 'Paroaria gularis');
insert into pet (name, animal, race) values ('Mà', 'Cockatoo, red-breasted', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Réservés', 'Roseate cockatoo', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Thérèse', 'Black-tailed tree creeper', 'Climacteris melanura');
insert into pet (name, animal, race) values ('Gaétane', 'Ocelot', 'Felis pardalis');
insert into pet (name, animal, race) values ('Clémence', 'Deer, red', 'Cervus elaphus');
insert into pet (name, animal, race) values ('Anaël', 'Chacma baboon', 'Papio ursinus');
insert into pet (name, animal, race) values ('Céline', 'White-tailed deer', 'Odocoilenaus virginianus');
insert into pet (name, animal, race) values ('Thérèse', 'Bandicoot, long-nosed', 'Perameles nasuta');
insert into pet (name, animal, race) values ('Måns', 'Armadillo, common long-nosed', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Mélissandre', 'Western patch-nosed snake', 'Salvadora hexalepis');
insert into pet (name, animal, race) values ('Måns', 'Rhea, greater', 'Rhea americana');
insert into pet (name, animal, race) values ('Géraldine', 'African fish eagle', 'Haliaetus vocifer');
insert into pet (name, animal, race) values ('Mélissandre', 'Flying fox (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Régine', 'Radiated tortoise', 'Geochelone radiata');
insert into pet (name, animal, race) values ('Tú', 'Finch, common melba', 'Pytilia melba');
insert into pet (name, animal, race) values ('Pål', 'Large cormorant', 'Phalacrocorax carbo');
insert into pet (name, animal, race) values ('Simplifiés', 'Asian false vampire bat', 'Megaderma spasma');
insert into pet (name, animal, race) values ('Estève', 'Cape starling', 'Lamprotornis nitens');
insert into pet (name, animal, race) values ('Annotés', 'Red and blue macaw', 'Ara chloroptera');
insert into pet (name, animal, race) values ('Lóng', 'Malabar squirrel', 'Ratufa indica');
insert into pet (name, animal, race) values ('Jú', 'Sparrow, rufous-collared', 'Zonotrichia capensis');
insert into pet (name, animal, race) values ('Torbjörn', 'Spectacled caiman', 'Caiman crocodilus');
insert into pet (name, animal, race) values ('Maéna', 'Deer, savannah', 'Mazama gouazoubira');
insert into pet (name, animal, race) values ('Märta', 'Giant girdled lizard', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Adélaïde', 'Darter, african', 'Anhinga rufa');
insert into pet (name, animal, race) values ('Dafnée', 'Springbuck', 'Antidorcas marsupialis');
insert into pet (name, animal, race) values ('Marlène', 'Green-backed heron', 'Butorides striatus');
insert into pet (name, animal, race) values ('Anaé', 'White-winged black tern', 'Chlidonias leucopterus');
insert into pet (name, animal, race) values ('Irène', 'Egyptian viper', 'Naja haje');
insert into pet (name, animal, race) values ('Görel', 'Grey lourie', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Örjan', 'Crow, house', 'Corvus brachyrhynchos');
insert into pet (name, animal, race) values ('Béatrice', 'Ferruginous hawk', 'Buteo regalis');
insert into pet (name, animal, race) values ('Desirée', 'Trumpeter, dark-winged', 'Psophia viridis');
insert into pet (name, animal, race) values ('Esbjörn', 'Heron, yellow-crowned night', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Frédérique', 'Giant armadillo', 'Priodontes maximus');
insert into pet (name, animal, race) values ('Mégane', 'Jaguar', 'Panthera onca');
insert into pet (name, animal, race) values ('Maïlys', 'Elegant crested tinamou', 'Eudromia elegans');
insert into pet (name, animal, race) values ('Annotés', 'Three-banded plover', 'Charadrius tricollaris');
insert into pet (name, animal, race) values ('Clémentine', 'Buffalo, asian water', 'Bubalus arnee');
insert into pet (name, animal, race) values ('Solène', 'Hoopoe, eurasian', 'Upupa epops');
insert into pet (name, animal, race) values ('Mylène', 'Spectacled caiman', 'Caiman crocodilus');
insert into pet (name, animal, race) values ('Josée', 'Galapagos sea lion', 'Zalophus californicus');
insert into pet (name, animal, race) values ('Yáo', 'Roller, lilac-breasted', 'Coracias caudata');
insert into pet (name, animal, race) values ('Kallisté', 'Stork, greater adjutant', 'Leptoptilus dubius');
insert into pet (name, animal, race) values ('Géraldine', 'Spotted hyena', 'Crocuta crocuta');
insert into pet (name, animal, race) values ('Léa', 'Malay squirrel (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Lèi', 'Raven, cape', 'Corvus albicollis');
insert into pet (name, animal, race) values ('Rachèle', 'Robin, white-throated', 'Irania gutteralis');
insert into pet (name, animal, race) values ('Miléna', 'Waved albatross', 'Diomedea irrorata');
insert into pet (name, animal, race) values ('Naéva', 'Bobcat', 'Felis rufus');
insert into pet (name, animal, race) values ('Annotés', 'Red-breasted cockatoo', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Marie-thérèse', 'Jaguar', 'Panthera onca');
insert into pet (name, animal, race) values ('Laurélie', 'Mara', 'Dolichitus patagonum');
insert into pet (name, animal, race) values ('Dorothée', 'Duiker, common', 'Sylvicapra grimma');
insert into pet (name, animal, race) values ('Maï', 'Frog (unidentified)', 'Rana sp.');
insert into pet (name, animal, race) values ('Pål', 'Stork, black-necked', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Miléna', 'Southern tamandua', 'Tamandua tetradactyla');
insert into pet (name, animal, race) values ('Lài', 'Polecat, african', 'Ictonyx striatus');
insert into pet (name, animal, race) values ('Åsa', 'Gerenuk', 'Litrocranius walleri');
insert into pet (name, animal, race) values ('Bérengère', 'Giant girdled lizard', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Frédérique', 'Otter, brazilian', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Uò', 'American black bear', 'Ursus americanus');
insert into pet (name, animal, race) values ('Stéphanie', 'Oriental white-backed vulture', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('André', 'Eagle, pallas''s fish', 'Haliaeetus leucoryphus');
insert into pet (name, animal, race) values ('Eliès', 'Cobra, egyptian', 'Naja haje');
insert into pet (name, animal, race) values ('Ruì', 'Genet, small-spotted', 'Genetta genetta');
insert into pet (name, animal, race) values ('Judicaël', 'Crow, american', 'Corvus brachyrhynchos');
insert into pet (name, animal, race) values ('Táng', 'Civet, common palm', 'Paradoxurus hermaphroditus');
insert into pet (name, animal, race) values ('Illustrée', 'Greater rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Mélanie', 'Pintail, bahama', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Agnès', 'Ringtail cat', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Hélène', 'African ground squirrel (unidentified)', 'Xerus sp.');
insert into pet (name, animal, race) values ('Marie-josée', 'Blackish oystercatcher', 'Haematopus ater');
insert into pet (name, animal, race) values ('Maïly', 'Snow goose', 'Anser caerulescens');
insert into pet (name, animal, race) values ('Maéna', 'Miner''s cat', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Mélia', 'Fox, cape', 'Vulpes chama');
insert into pet (name, animal, race) values ('Clémentine', 'Hippopotamus', 'Hippopotamus amphibius');
insert into pet (name, animal, race) values ('Maëlyss', 'Otter, brazilian', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Dà', 'Ring-tailed lemur', 'Lemur catta');
insert into pet (name, animal, race) values ('Bérangère', 'Hartebeest, coke''s', 'Alcelaphus buselaphus cokii');
insert into pet (name, animal, race) values ('Célestine', 'Kirk''s dik dik', 'Madoqua kirkii');
insert into pet (name, animal, race) values ('Adèle', 'White-cheeked pintail', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Aí', 'Jabiru stork', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Eliès', 'Springbuck', 'Antidorcas marsupialis');
insert into pet (name, animal, race) values ('Anaé', 'American bighorn sheep', 'Ovis canadensis');
insert into pet (name, animal, race) values ('Régine', 'Steller''s sea lion', 'Eumetopias jubatus');
insert into pet (name, animal, race) values ('Lài', 'Gecko, bent-toed', 'Cyrtodactylus louisiadensis');
insert into pet (name, animal, race) values ('Maï', 'Fox, grey', 'Vulpes cinereoargenteus');
insert into pet (name, animal, race) values ('Tán', 'Eurasian beaver', 'Castor fiber');
insert into pet (name, animal, race) values ('Frédérique', 'Stork, black-necked', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Véronique', 'Western lowland gorilla', 'Gorilla gorilla');
insert into pet (name, animal, race) values ('Simplifiés', 'Nelson ground squirrel', 'Ammospermophilus nelsoni');
insert into pet (name, animal, race) values ('Illustrée', 'Black-tailed tree creeper', 'Climacteris melanura');
insert into pet (name, animal, race) values ('Océane', 'Phascogale, brush-tailed', 'Phascogale tapoatafa');
insert into pet (name, animal, race) values ('Réservés', 'Gull, kelp', 'Larus dominicanus');
insert into pet (name, animal, race) values ('Noémie', 'Armadillo, seven-banded', 'Dasypus septemcincus');
insert into pet (name, animal, race) values ('Björn', 'Jackrabbit, white-tailed', 'Lepus townsendii');
insert into pet (name, animal, race) values ('Gérald', 'Dove, rock', 'Columba livia');
insert into pet (name, animal, race) values ('Pélagie', 'Burmese brown mountain tortoise', 'Manouria emys');
insert into pet (name, animal, race) values ('Frédérique', 'Brush-tailed rat kangaroo', 'Bettongia penicillata');
insert into pet (name, animal, race) values ('Léana', 'Agile wallaby', 'Macropus agilis');
insert into pet (name, animal, race) values ('Anaëlle', 'Mongoose, banded', 'Mungos mungo');
insert into pet (name, animal, race) values ('Bécassine', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Régine', 'Black bear', 'Ursus americanus');
insert into pet (name, animal, race) values ('Börje', 'Squirrel, eastern fox', 'Sciurus niger');
insert into pet (name, animal, race) values ('Stéphanie', 'Pintail, white-cheeked', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Åslög', 'Peccary, collared', 'Tayassu tajacu');
insert into pet (name, animal, race) values ('Andrée', 'Coatimundi, white-nosed', 'Nasua narica');
insert into pet (name, animal, race) values ('Régine', 'Indian jackal', 'Canis aureus');
insert into pet (name, animal, race) values ('Maëlann', 'Falcon, peregrine', 'Falco peregrinus');
insert into pet (name, animal, race) values ('Clémence', 'Northern phalarope', 'Phalaropus lobatus');
insert into pet (name, animal, race) values ('Uò', 'Black-faced kangaroo', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Daphnée', 'European red squirrel', 'Sciurus vulgaris');
insert into pet (name, animal, race) values ('Andréanne', 'Anteater, australian spiny', 'Tachyglossus aculeatus');
insert into pet (name, animal, race) values ('Pò', 'Anteater, australian spiny', 'Tachyglossus aculeatus');
insert into pet (name, animal, race) values ('Cléopatre', 'Eagle, bald', 'Haliaeetus leucocephalus');
insert into pet (name, animal, race) values ('Méghane', 'Bunting, crested', 'Melophus lathami');
insert into pet (name, animal, race) values ('Séréna', 'Kudu, greater', 'Tragelaphus strepsiceros');
insert into pet (name, animal, race) values ('Judicaël', 'Stork, jabiru', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Valérie', 'Bustard, kori', 'Choriotis kori');
insert into pet (name, animal, race) values ('Méthode', 'Deer, white-tailed', 'Odocoilenaus virginianus');
insert into pet (name, animal, race) values ('Estée', 'Glossy ibis', 'Plegadis falcinellus');
insert into pet (name, animal, race) values ('Gaëlle', 'Cobra (unidentified)', 'Naja sp.');
insert into pet (name, animal, race) values ('Médiamass', 'Hornbill, southern ground', 'Bucorvus leadbeateri');
insert into pet (name, animal, race) values ('Gaïa', 'Boa, columbian rainbow', 'Epicrates cenchria maurus');
insert into pet (name, animal, race) values ('Annotés', 'Chuckwalla', 'Sauromalus obesus');
insert into pet (name, animal, race) values ('Joséphine', 'Black-eyed bulbul', 'Pycnonotus barbatus');
insert into pet (name, animal, race) values ('Réjane', 'Spur-winged goose', 'Plectopterus gambensis');
insert into pet (name, animal, race) values ('Erwéi', 'Hummingbird (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Lóng', 'African lynx', 'Felis caracal');
insert into pet (name, animal, race) values ('André', 'Crane, wattled', 'Bugeranus caruncalatus');
insert into pet (name, animal, race) values ('Pò', 'Barrows goldeneye', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Mélinda', 'Long-finned pilot whale', 'Globicephala melas');
insert into pet (name, animal, race) values ('Ophélie', 'Ringtail, common', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Léone', 'Opossum, american virginia', 'Didelphis virginiana');
insert into pet (name, animal, race) values ('Rachèle', 'Bontebok', 'Damaliscus dorcas');
insert into pet (name, animal, race) values ('Clélia', 'Australian sea lion', 'Neophoca cinerea');
insert into pet (name, animal, race) values ('Erwéi', 'Snow goose', 'Anser caerulescens');
insert into pet (name, animal, race) values ('Nadège', 'Southern white-crowned shrike', 'Eurocephalus anguitimens');
insert into pet (name, animal, race) values ('Dafnée', 'White-cheeked pintail', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Magdalène', 'Whale, baleen', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Eloïse', 'Yellow-bellied marmot', 'Marmota flaviventris');
insert into pet (name, animal, race) values ('Lài', 'Tiger snake', 'Notechis semmiannulatus');
insert into pet (name, animal, race) values ('Maëlys', 'Cobra (unidentified)', 'Naja sp.');
insert into pet (name, animal, race) values ('Nuó', 'Hoopoe, eurasian', 'Upupa epops');
insert into pet (name, animal, race) values ('Marie-josée', 'Olive baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Thérèse', 'Ibis, sacred', 'Threskionis aethiopicus');
insert into pet (name, animal, race) values ('Yénora', 'White-tailed jackrabbit', 'Lepus townsendii');
insert into pet (name, animal, race) values ('Hélèna', 'African fish eagle', 'Haliaetus vocifer');
insert into pet (name, animal, race) values ('Clémentine', 'Frogmouth, tawny', 'Podargus strigoides');
insert into pet (name, animal, race) values ('Josée', 'Crane, wattled', 'Bugeranus caruncalatus');
insert into pet (name, animal, race) values ('Örjan', 'Red howler monkey', 'Alouatta seniculus');
insert into pet (name, animal, race) values ('Andrée', 'Lion, african', 'Panthera leo');
insert into pet (name, animal, race) values ('Marie-ève', 'Square-lipped rhinoceros', 'Ceratotherium simum');
insert into pet (name, animal, race) values ('Lèi', 'Common wallaroo', 'Macropus robustus');
insert into pet (name, animal, race) values ('Félicie', 'Yellow-billed hornbill', 'Tockus flavirostris');
insert into pet (name, animal, race) values ('Eliès', 'Mountain duck', 'Hymenolaimus malacorhynchus');
insert into pet (name, animal, race) values ('Maïly', 'Crane, wattled', 'Bugeranus caruncalatus');
insert into pet (name, animal, race) values ('Athéna', 'Brazilian otter', 'Pteronura brasiliensis');
insert into pet (name, animal, race) values ('Yóu', 'Violet-crested turaco', 'Tauraco porphyrelophus');
insert into pet (name, animal, race) values ('Ruì', 'Eagle, bald', 'Haliaeetus leucocephalus');
insert into pet (name, animal, race) values ('Mårten', 'Shrike, common boubou', 'Laniarius ferrugineus');
insert into pet (name, animal, race) values ('Naëlle', 'Pied butcher bird', 'Cracticus nigroagularis');
insert into pet (name, animal, race) values ('Gisèle', 'Armadillo, seven-banded', 'Dasypus septemcincus');
insert into pet (name, animal, race) values ('Lyséa', 'Topi', 'Damaliscus lunatus');
insert into pet (name, animal, race) values ('Océanne', 'Whale, killer', 'Orcinus orca');
insert into pet (name, animal, race) values ('Mélys', 'Levaillant''s barbet', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Andrée', 'Eagle, bateleur', 'Terathopius ecaudatus');
insert into pet (name, animal, race) values ('Torbjörn', 'Grenadier, common', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Lài', 'Paca', 'Agouti paca');
insert into pet (name, animal, race) values ('Miléna', 'Yellow-crowned night heron', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Yè', 'Common grenadier', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Cléa', 'Dolphin, striped', 'Stenella coeruleoalba');
insert into pet (name, animal, race) values ('Geneviève', 'Crab-eating raccoon', 'Procyon cancrivorus');
insert into pet (name, animal, race) values ('Pò', 'Hedgehog, south african', 'Erinaceus frontalis');
insert into pet (name, animal, race) values ('Josée', 'Capuchin, weeper', 'Cebus nigrivittatus');
insert into pet (name, animal, race) values ('Adélie', 'Ringtail cat', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Pål', 'Dog, black-tailed prairie', 'Cynomys ludovicianus');
insert into pet (name, animal, race) values ('Marie-thérèse', 'Trumpeter, dark-winged', 'Psophia viridis');
insert into pet (name, animal, race) values ('Loïca', 'Arctic tern', 'Sterna paradisaea');
insert into pet (name, animal, race) values ('Andréanne', 'Komodo dragon', 'Varanus komodensis');
insert into pet (name, animal, race) values ('Andrée', 'Kookaburra, laughing', 'Dacelo novaeguineae');
insert into pet (name, animal, race) values ('Solène', 'Red-tailed wambenger', 'Phascogale calura');
insert into pet (name, animal, race) values ('Geneviève', 'Squirrel, richardson''s ground', 'Spermophilus richardsonii');
insert into pet (name, animal, race) values ('Yóu', 'Fairy penguin', 'Eudyptula minor');
insert into pet (name, animal, race) values ('Hélène', 'Insect, stick', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Cloé', 'Sungazer, yellow-brown', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Desirée', 'Raven, white-necked', 'Corvus albicollis');
insert into pet (name, animal, race) values ('Bérénice', 'Savanna baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Görel', 'Fringe-eared oryx', 'Oryx gazella callotis');
insert into pet (name, animal, race) values ('Camélia', 'Vulture, bengal', 'Gyps bengalensis');
insert into pet (name, animal, race) values ('Yè', 'Yellow-crowned night heron', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Angélique', 'Red sheep', 'Ovis ammon');
insert into pet (name, animal, race) values ('Lài', 'Swallow (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Mélodie', 'Snake, western patch-nosed', 'Salvadora hexalepis');
insert into pet (name, animal, race) values ('Marylène', 'Australian brush turkey', 'Alectura lathami');
insert into pet (name, animal, race) values ('Séréna', 'Komodo dragon', 'Varanus komodensis');
insert into pet (name, animal, race) values ('Geneviève', 'Stork, black-necked', 'Ephippiorhynchus mycteria');
insert into pet (name, animal, race) values ('Léane', 'Hanuman langur', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Wá', 'Macaw, red and blue', 'Ara chloroptera');
insert into pet (name, animal, race) values ('Josée', 'Skimmer, four-spotted', 'Libellula quadrimaculata');
insert into pet (name, animal, race) values ('Véronique', 'Red meerkat', 'Cynictis penicillata');
insert into pet (name, animal, race) values ('Anaé', 'Bunting, crested', 'Melophus lathami');
insert into pet (name, animal, race) values ('Eugénie', 'Crocodile, nile', 'Crocodylus niloticus');
insert into pet (name, animal, race) values ('Angèle', 'Scarlet macaw', 'Ara macao');
insert into pet (name, animal, race) values ('Fèi', 'Thrasher, curve-billed', 'Toxostoma curvirostre');
insert into pet (name, animal, race) values ('Chloé', 'Mexican boa', 'Boa constrictor mexicana');
insert into pet (name, animal, race) values ('Chloé', 'Spectacled caiman', 'Caiman crocodilus');
insert into pet (name, animal, race) values ('Mélina', 'Kinkajou', 'Potos flavus');
insert into pet (name, animal, race) values ('Maïwenn', 'Hudsonian godwit', 'Limosa haemastica');
insert into pet (name, animal, race) values ('Loïc', 'White-winged dove', 'Zenaida asiatica');
insert into pet (name, animal, race) values ('Lorène', 'Fox, north american red', 'Vulpes vulpes');
insert into pet (name, animal, race) values ('Marie-noël', 'Rhinoceros, square-lipped', 'Ceratotherium simum');
insert into pet (name, animal, race) values ('Börje', 'Brown hyena', 'Hyaena brunnea');
insert into pet (name, animal, race) values ('Solène', 'Giant armadillo', 'Priodontes maximus');
insert into pet (name, animal, race) values ('Kù', 'Woolly-necked stork', 'Ciconia episcopus');
insert into pet (name, animal, race) values ('Marylène', 'Sage grouse', 'Centrocercus urophasianus');
insert into pet (name, animal, race) values ('Frédérique', 'White-throated monitor', 'Varanus albigularis');
insert into pet (name, animal, race) values ('Léane', 'Colobus, white-mantled', 'Colobus guerza');
insert into pet (name, animal, race) values ('Maëly', 'South American puma', 'Felis concolor');
insert into pet (name, animal, race) values ('Cécilia', 'Alligator, mississippi', 'Alligator mississippiensis');
insert into pet (name, animal, race) values ('Léonore', 'Badger, eurasian', 'Meles meles');
insert into pet (name, animal, race) values ('Maïlis', 'Dolphin, common', 'Delphinus delphis');
insert into pet (name, animal, race) values ('Adèle', 'Buffalo, american', 'Bison bison');
insert into pet (name, animal, race) values ('Félicie', 'Macaque, rhesus', 'Macaca mulatta');
insert into pet (name, animal, race) values ('Björn', 'Beaver, european', 'Castor fiber');
insert into pet (name, animal, race) values ('Esbjörn', 'Sloth, two-toed', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Miléna', 'Boa, emerald green tree', 'Boa caninus');
insert into pet (name, animal, race) values ('Solène', 'Greylag goose', 'Anser anser');
insert into pet (name, animal, race) values ('Adélie', 'Spoonbill, european', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Mégane', 'Arctic lemming', 'Dicrostonyx groenlandicus');
insert into pet (name, animal, race) values ('Chloé', 'Baleen whale', 'Eubalaena australis');
insert into pet (name, animal, race) values ('Judicaël', 'Honey badger', 'Mellivora capensis');
insert into pet (name, animal, race) values ('Kuí', 'Asian foreset tortoise', 'Manouria emys');
insert into pet (name, animal, race) values ('Cécilia', 'Brazilian tapir', 'Tapirus terrestris');
insert into pet (name, animal, race) values ('Faîtes', 'Savannah deer (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Sòng', 'Mountain goat', 'Oreamnos americanus');
insert into pet (name, animal, race) values ('Garçon', 'Hyrax', 'Dendrohyrax brucel');
insert into pet (name, animal, race) values ('Mårten', 'Pronghorn', 'Antilocapra americana');
insert into pet (name, animal, race) values ('Mà', 'Barrows goldeneye', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Clélia', 'Springhare', 'Pedetes capensis');
insert into pet (name, animal, race) values ('Yáo', 'European spoonbill', 'Platalea leucordia');
insert into pet (name, animal, race) values ('Mélodie', 'Starling, greater blue-eared', 'Lamprotornis chalybaeus');
insert into pet (name, animal, race) values ('Maëlyss', 'Stork, yellow-billed', 'Mycteria ibis');
insert into pet (name, animal, race) values ('Mà', 'Flamingo, lesser', 'Phoeniconaias minor');
insert into pet (name, animal, race) values ('Ophélie', 'Ringtail, common', 'Pseudocheirus peregrinus');
insert into pet (name, animal, race) values ('Sòng', 'Common nighthawk', 'Chordeiles minor');
insert into pet (name, animal, race) values ('Almérinda', 'Red-knobbed coot', 'Fulica cristata');
insert into pet (name, animal, race) values ('Danièle', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Dafnée', 'Cape fox', 'Vulpes chama');
insert into pet (name, animal, race) values ('Adélaïde', 'Goose, canada', 'Branta canadensis');
insert into pet (name, animal, race) values ('Örjan', 'Galapagos penguin', 'Spheniscus mendiculus');
insert into pet (name, animal, race) values ('Mélia', 'Gazelle, grant''s', 'Gazella granti');
insert into pet (name, animal, race) values ('Cécile', 'White-cheeked pintail', 'Anas bahamensis');
insert into pet (name, animal, race) values ('Françoise', 'Deer, white-tailed', 'Odocoilenaus virginianus');
insert into pet (name, animal, race) values ('Gisèle', 'Two-toed tree sloth', 'Choloepus hoffmani');
insert into pet (name, animal, race) values ('Lèi', 'Pheasant, ring-necked', 'Phasianus colchicus');
insert into pet (name, animal, race) values ('Adèle', 'Cormorant (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Sòng', 'North American red fox', 'Vulpes vulpes');
insert into pet (name, animal, race) values ('Yú', 'Phalarope, grey', 'Phalaropus fulicarius');
insert into pet (name, animal, race) values ('Kù', 'Common goldeneye', 'Bucephala clangula');
insert into pet (name, animal, race) values ('Félicie', 'Golden brush-tailed possum', 'Trichosurus vulpecula');
insert into pet (name, animal, race) values ('Håkan', 'Vicuna', 'Vicugna vicugna');
insert into pet (name, animal, race) values ('Yáo', 'Cobra, egyptian', 'Naja haje');
insert into pet (name, animal, race) values ('Méthode', 'Wallaby, river', 'Macropus agilis');
insert into pet (name, animal, race) values ('Hélène', 'Ringtail', 'Bassariscus astutus');
insert into pet (name, animal, race) values ('Lucrèce', 'Vulture, egyptian', 'Neophron percnopterus');
insert into pet (name, animal, race) values ('Frédérique', 'Monitor, water', 'Varanus salvator');
insert into pet (name, animal, race) values ('Agnès', 'Asian openbill', 'Anastomus oscitans');
insert into pet (name, animal, race) values ('Aurélie', 'Gazer, sun', 'Cordylus giganteus');
insert into pet (name, animal, race) values ('Mégane', 'Common eland', 'Taurotagus oryx');
insert into pet (name, animal, race) values ('Aurélie', 'Gnu, brindled', 'Connochaetus taurinus');
insert into pet (name, animal, race) values ('Anaëlle', 'Asian elephant', 'Elephas maximus bengalensis');
insert into pet (name, animal, race) values ('Andréa', 'Royal tern', 'Thalasseus maximus');
insert into pet (name, animal, race) values ('Danièle', 'Francolin, coqui', 'Francolinus coqui');
insert into pet (name, animal, race) values ('Annotés', 'Worm snake (unidentified)', 'Carphophis sp.');
insert into pet (name, animal, race) values ('Åslög', 'Weaver, chestnut', 'Ploceus rubiginosus');
insert into pet (name, animal, race) values ('Médiamass', 'Squirrel, eastern fox', 'Sciurus niger');
insert into pet (name, animal, race) values ('Néhémie', 'Grenadier, common', 'Uraeginthus granatina');
insert into pet (name, animal, race) values ('Méthode', 'Dingo', 'Canis dingo');
insert into pet (name, animal, race) values ('Maëlla', 'African fish eagle', 'Haliaetus vocifer');
insert into pet (name, animal, race) values ('Mélodie', 'Peacock, blue', 'Pavo cristatus');
insert into pet (name, animal, race) values ('Médiamass', 'Great horned owl', 'Bubo virginianus');
insert into pet (name, animal, race) values ('Estée', 'Green-winged trumpeter', 'Psophia viridis');
insert into pet (name, animal, race) values ('Marie-thérèse', 'Sheep, stone', 'Ovis dalli stonei');
insert into pet (name, animal, race) values ('Crééz', 'Dove, ring', 'Columba palumbus');
insert into pet (name, animal, race) values ('Vérane', 'Grey heron', 'Ardea cinerea');
insert into pet (name, animal, race) values ('Jú', 'Gecko (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Yú', 'Knob-nosed goose', 'Sarkidornis melanotos');
insert into pet (name, animal, race) values ('Lèi', 'Painted stork', 'Mycteria leucocephala');
insert into pet (name, animal, race) values ('Lucrèce', 'Nile crocodile', 'Crocodylus niloticus');
insert into pet (name, animal, race) values ('Maïlis', 'Black-faced kangaroo', 'Macropus fuliginosus');
insert into pet (name, animal, race) values ('Kévina', 'Rhea, gray', 'Rhea americana');
insert into pet (name, animal, race) values ('Andréanne', 'Salmon, sockeye', 'Oncorhynchus nerka');
insert into pet (name, animal, race) values ('Eugénie', 'Porcupine, north american', 'Erethizon dorsatum');
insert into pet (name, animal, race) values ('Méghane', 'Cormorant, large', 'Phalacrocorax carbo');
insert into pet (name, animal, race) values ('Léane', 'Mouse, four-striped grass', 'Rhabdomys pumilio');
insert into pet (name, animal, race) values ('Rachèle', 'Swainson''s francolin', 'Francolinus swainsonii');
insert into pet (name, animal, race) values ('Gaëlle', 'Turtle (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Illustrée', 'Galapagos dove', 'Zenaida galapagoensis');
insert into pet (name, animal, race) values ('Rébecca', 'Galah', 'Eolophus roseicapillus');
insert into pet (name, animal, race) values ('Simplifiés', 'Pelican, eastern white', 'Pelecans onocratalus');
insert into pet (name, animal, race) values ('Ráo', 'Dog, african wild', 'Lycaon pictus');
insert into pet (name, animal, race) values ('Annotée', 'Northern fur seal', 'Callorhinus ursinus');
insert into pet (name, animal, race) values ('Almérinda', 'Otter, canadian river', 'Lutra canadensis');
insert into pet (name, animal, race) values ('Publicité', 'Yellow baboon', 'Papio cynocephalus');
insert into pet (name, animal, race) values ('Thérèsa', 'Langur, gray', 'Semnopithecus entellus');
insert into pet (name, animal, race) values ('Léane', 'Savanna fox', 'Dusicyon thous');
insert into pet (name, animal, race) values ('Åke', 'Bear, sloth', 'Melursus ursinus');
insert into pet (name, animal, race) values ('Laïla', 'Long-billed cockatoo', 'Cacatua tenuirostris');
insert into pet (name, animal, race) values ('Mélina', 'Lapwing (unidentified)', 'Vanellus sp.');
insert into pet (name, animal, race) values ('Håkan', 'Marmot, hoary', 'Marmota caligata');
insert into pet (name, animal, race) values ('Cécilia', 'Crown of thorns starfish', 'Acanthaster planci');
insert into pet (name, animal, race) values ('Laurélie', 'Bear, grizzly', 'Ursus arctos');
insert into pet (name, animal, race) values ('Alizée', 'Prehensile-tailed porcupine', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Camélia', 'Grey lourie', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Géraldine', 'Finch, common melba', 'Pytilia melba');
insert into pet (name, animal, race) values ('Rachèle', 'Prehensile-tailed porcupine', 'Coendou prehensilis');
insert into pet (name, animal, race) values ('Maëlle', 'Leopard, indian', 'Panthera pardus');
insert into pet (name, animal, race) values ('Rébecca', 'Amazon parrot (unidentified)', 'Amazona sp.');
insert into pet (name, animal, race) values ('Athéna', 'Hornbill, red-billed', 'Tockus erythrorhyncus');
insert into pet (name, animal, race) values ('Garçon', 'Common pheasant', 'Phasianus colchicus');
insert into pet (name, animal, race) values ('Mårten', 'Pigeon, wood', 'Columba palumbus');
insert into pet (name, animal, race) values ('Mélanie', 'Common rhea', 'Rhea americana');
insert into pet (name, animal, race) values ('Dù', 'Lizard, blue-tongued', 'Tiliqua scincoides');
insert into pet (name, animal, race) values ('Méline', 'Phalarope, grey', 'Phalaropus fulicarius');
insert into pet (name, animal, race) values ('Cunégonde', 'Polecat, african', 'Ictonyx striatus');
insert into pet (name, animal, race) values ('Örjan', 'Booby, blue-footed', 'Sula nebouxii');
insert into pet (name, animal, race) values ('Geneviève', 'Eastern boa constrictor', 'Acrantophis madagascariensis');
insert into pet (name, animal, race) values ('Dù', 'Monkey, vervet', 'Cercopithecus aethiops');
insert into pet (name, animal, race) values ('Marie-thérèse', 'Gazelle, thomson''s', 'Gazella thompsonii');
insert into pet (name, animal, race) values ('Yáo', 'White-throated monitor', 'Varanus albigularis');
insert into pet (name, animal, race) values ('Adélaïde', 'Starfish, crown of thorns', 'Acanthaster planci');
insert into pet (name, animal, race) values ('Méryl', 'Purple moorhen', 'Porphyrio porphyrio');
insert into pet (name, animal, race) values ('Dorothée', 'Silver-backed jackal', 'Canis mesomelas');
insert into pet (name, animal, race) values ('Lèi', 'Snake, tiger', 'Notechis semmiannulatus');
insert into pet (name, animal, race) values ('Daphnée', 'Asian openbill', 'Anastomus oscitans');
insert into pet (name, animal, race) values ('Joséphine', 'Comb duck', 'Sarkidornis melanotos');
insert into pet (name, animal, race) values ('Mårten', 'Grison', 'Galictis vittata');
insert into pet (name, animal, race) values ('Stévina', 'Lion, african', 'Panthera leo');
insert into pet (name, animal, race) values ('Kù', 'Ostrich', 'Struthio camelus');
insert into pet (name, animal, race) values ('Françoise', 'Brown and yellow marshbird', 'Pseudoleistes virescens');
insert into pet (name, animal, race) values ('Hélèna', 'Ant (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Vénus', 'Yellow-billed stork', 'Mycteria ibis');
insert into pet (name, animal, race) values ('Cléopatre', 'Greater adjutant stork', 'Leptoptilus dubius');
insert into pet (name, animal, race) values ('Frédérique', 'Common waterbuck', 'Kobus defassa');
insert into pet (name, animal, race) values ('Géraldine', 'Galapagos hawk', 'Buteo galapagoensis');
insert into pet (name, animal, race) values ('Bénédicte', 'Gerbil (unidentified)', 'Gerbillus sp.');
insert into pet (name, animal, race) values ('Desirée', 'Stork, woolly-necked', 'Ciconia episcopus');
insert into pet (name, animal, race) values ('Kuí', 'Weeper capuchin', 'Cebus nigrivittatus');
insert into pet (name, animal, race) values ('Néhémie', 'Blue and yellow macaw', 'Ara ararauna');
insert into pet (name, animal, race) values ('Athéna', 'Civet (unidentified)', 'unavailable');
insert into pet (name, animal, race) values ('Loïc', 'Armadillo, nine-banded', 'Dasypus novemcinctus');
insert into pet (name, animal, race) values ('Östen', 'Cape wild cat', 'Felis libyca');
insert into pet (name, animal, race) values ('Aloïs', 'Insect, stick', 'Leprocaulinus vipera');
insert into pet (name, animal, race) values ('Stéphanie', 'White-winged dove', 'Zenaida asiatica');
insert into pet (name, animal, race) values ('Angélique', 'Snake, tiger', 'Notechis semmiannulatus');
insert into pet (name, animal, race) values ('Méline', 'Squirrel, african bush', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Eliès', 'Snake, racer', 'Coluber constrictor');
insert into pet (name, animal, race) values ('Athéna', 'Kangaroo, eastern grey', 'Macropus giganteus');
insert into pet (name, animal, race) values ('Mélanie', 'Lappet-faced vulture', 'Aegypius tracheliotus');
insert into pet (name, animal, race) values ('Bécassine', 'Onager', 'Equus hemionus');
insert into pet (name, animal, race) values ('Anaé', 'Tarantula', 'Lasiodora parahybana');
insert into pet (name, animal, race) values ('Andréanne', 'Barbet, levaillant''s', 'Trachyphonus vaillantii');
insert into pet (name, animal, race) values ('Joséphine', 'Lourie, grey', 'Lorythaixoides concolor');
insert into pet (name, animal, race) values ('Bénédicte', 'Mountain duck', 'Hymenolaimus malacorhynchus');
insert into pet (name, animal, race) values ('Göran', 'Squirrel, african bush', 'Paraxerus cepapi');
insert into pet (name, animal, race) values ('Loïca', 'Water legaan', 'Varanus salvator');
insert into pet (name, animal, race) values ('Bécassine', 'Heron, yellow-crowned night', 'Nyctanassa violacea');
insert into pet (name, animal, race) values ('Maïwenn', 'White-throated monitor', 'Varanus albigularis');
insert into pet (name, animal, race) values ('Publicité', 'Lilac-breasted roller', 'Coracias caudata');
insert into pet (name, animal, race) values ('Nadège', 'Least chipmunk', 'Eutamias minimus');
insert into pet (name, animal, race) values ('Garçon', 'Small-spotted genet', 'Genetta genetta');
insert into pet (name, animal, race) values ('Océanne', 'Fox, grey', 'Vulpes cinereoargenteus');
insert into pet (name, animal, race) values ('Marie-ève', 'Kangaroo, red', 'Macropus rufus');
insert into pet (name, animal, race) values ('Méryl', 'Eagle, bald', 'Haliaeetus leucocephalus');
insert into pet (name, animal, race) values ('Nélie', 'White-tailed jackrabbit', 'Lepus townsendii');
insert into pet (name, animal, race) values ('Åsa', 'Water monitor', 'Varanus salvator');
